'------------------------------------------------------------------------------
' <auto-generated>
'     此代码由工具生成。
'     运行时版本:4.0.30319.42000
'
'     对此文件的更改可能会导致不正确的行为，并且如果
'     重新生成代码，这些更改将会丢失。
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    '此类是由 StronglyTypedResourceBuilder
    '类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    '若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    '(以 /str 作为命令选项)，或重新生成 VS 项目。
    '''<summary>
    '''  一个强类型的资源类，用于查找本地化的字符串等。
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  返回此类使用的缓存的 ResourceManager 实例。
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("SMRUCC.proteomics.MS_Spectrum.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  使用此强类型资源类，为所有资源查找
        '''  重写当前线程的 CurrentUICulture 属性。
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  查找类似 var names = Object.keys(msms);  // 鑾峰彇寰楀埌浜嗘墍鏈夌殑璋卞浘鐨勫悕绉?
        '''
        '''$(document).ready(function () {
        '''	var name = names[0];
        '''	show(name);
        '''});
        '''
        '''function show(name) {
        '''	var data = msms[name];
        '''	var count = 0;	
        '''    var mid = &quot;&quot;;				// Pass
        '''    var mole = name;	// Pass molecule name here!
        '''    var chart = new Highcharts.Chart({
        '''        chart: {
        '''            renderTo: &apos;container&apos;,
        '''            defaultSeriesType: &apos;column&apos;,
        '''            zoomType: &apos;xy&apos;,
        '''            margin: [50, 50, 200, 80]
        '''        },
        '''        title:  [字符串的其余部分被截断]&quot;; 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property App() As String
            Get
                Return ResourceManager.GetString("App", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property attn() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("attn", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 var msms = $data; 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property data() As String
            Get
                Return ResourceManager.GetString("data", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 // Copyright 2006 Google Inc.
        '''//
        '''// Licensed under the Apache License, Version 2.0 (the &quot;License&quot;);
        '''// you may not use this file except in compliance with the License.
        '''// You may obtain a copy of the License at
        '''//
        '''//   http://www.apache.org/licenses/LICENSE-2.0
        '''//
        '''// Unless required by applicable law or agreed to in writing, software
        '''// distributed under the License is distributed on an &quot;AS IS&quot; BASIS,
        '''// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
        '''// See the License f [字符串的其余部分被截断]&quot;; 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property excanvas_compiled() As String
            Get
                Return ResourceManager.GetString("excanvas_compiled", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 ///////// DELTA BUILD ///////////
        '''/**
        ''' * Contains selection functionality
        ''' *
        ''' * Uses HC 1.2.4 and works with
        ''' *  fragment_chart.php
        ''' *  metabo_chart.php
        ''' *  neutral_chart.php
        ''' */
        '''
        '''
        '''// ==ClosureCompiler==
        '''// @compilation_level SIMPLE_OPTIMIZATIONS
        '''
        '''/** 
        ''' * @license Name:    Highcharts
        ''' * Version: 1.1.3 (2010-02-03)
        ''' * Author:  Vevstein Web
        ''' * Support: www.highcharts.com/support
        ''' * License: www.highcharts.com/license
        ''' */
        '''
        '''/* Bookmarks (Huu)
        ''' *
        ''' * 0: Global variables
        ''' * 1: Scaling of c [字符串的其余部分被截断]&quot;; 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property highcharts_src_delta() As String
            Get
                Return ResourceManager.GetString("highcharts_src_delta", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 &lt;!DOCTYPE html&gt;
        '''&lt;html&gt;
        '''&lt;head&gt;
        '''    &lt;meta http-equiv=&quot;Content-Type&quot; content=&quot;text/html; charset=utf-8&quot;&gt;
        '''    &lt;title&gt;Metabolite MSMS Chart&lt;/title&gt;
        '''
        '''    &lt;!-- 1. Add these JavaScript inclusions in the head of your page --&gt;
        '''    &lt;script type=&quot;text/javascript&quot; src=&quot;lib/jquery-1.6.1.min.js&quot;&gt;&lt;/script&gt;
        '''    &lt;script type=&quot;text/javascript&quot; src=&quot;lib/highcharts.src.delta.js&quot;&gt;&lt;/script&gt;
        '''    &lt;script type=&quot;text/javascript&quot; src=&quot;lib/excanvas.compiled.js&quot;&gt;&lt;/script&gt;
        '''    &lt;!--
        '''        &lt;script src=&quot;https://code.highcharts. [字符串的其余部分被截断]&quot;; 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property index() As String
            Get
                Return ResourceManager.GetString("index", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 /*!
        ''' * jQuery JavaScript Library v1.6.1
        ''' * http://jquery.com/
        ''' *
        ''' * Copyright 2011, John Resig
        ''' * Dual licensed under the MIT or GPL Version 2 licenses.
        ''' * http://jquery.org/license
        ''' *
        ''' * Includes Sizzle.js
        ''' * http://sizzlejs.com/
        ''' * Copyright 2011, The Dojo Foundation
        ''' * Released under the MIT, BSD, and GPL Licenses.
        ''' *
        ''' * Date: Thu May 12 15:04:36 2011 -0400
        ''' */
        '''(function(a,b){function cy(a){return f.isWindow(a)?a:a.nodeType===9?a.defaultView||a.parentWindow:!1}function cv(a){if(!cj[a]){var [字符串的其余部分被截断]&quot;; 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property jquery_1_6_1_min() As String
            Get
                Return ResourceManager.GetString("jquery_1_6_1_min", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
