var keggmap={
	"Metabolic pathways":{"classA":"1","classB":"1.0"},
	"Biosynthesis of secondary metabolites":{"classA":"1","classB":"1.0"},
	"Microbial metabolism in diverse environments":{"classA":"1","classB":"1.0"},
	"Carbon metabolism":{"classA":"1","classB":"1.0"},
	"2-Oxocarboxylic acid metabolism":{"classA":"1","classB":"1.0"},
	"Fatty acid metabolism":{"classA":"1","classB":"1.0"},
	"Biosynthesis of amino acids":{"classA":"1","classB":"1.0"},
	"Degradation of aromatic compounds":{"classA":"1","classB":"1.0"},
	"Glycolysis / Gluconeogenesis":{"classA":"1","classB":"1.1"},
	"Citrate cycle (TCA cycle)":{"classA":"1","classB":"1.1"},
	"Pentose phosphate pathway":{"classA":"1","classB":"1.1"},
	"Pentose and glucuronate interconversions":{"classA":"1","classB":"1.1"},
	"Fructose and mannose metabolism":{"classA":"1","classB":"1.1"},
	"Galactose metabolism":{"classA":"1","classB":"1.1"},
	"Ascorbate and aldarate metabolism":{"classA":"1","classB":"1.1"},
	"Starch and sucrose metabolism":{"classA":"1","classB":"1.1"},
	"Amino sugar and nucleotide sugar metabolism":{"classA":"1","classB":"1.1"},
	"Pyruvate metabolism":{"classA":"1","classB":"1.1"},
	"Glyoxylate and dicarboxylate metabolism":{"classA":"1","classB":"1.1"},
	"Propanoate metabolism":{"classA":"1","classB":"1.1"},
	"Butanoate metabolism":{"classA":"1","classB":"1.1"},
	"C5-Branched dibasic acid metabolism":{"classA":"1","classB":"1.1"},
	"Inositol phosphate metabolism":{"classA":"1","classB":"1.1"},
	"Oxidative phosphorylation":{"classA":"1","classB":"1.2"},
	"Photosynthesis":{"classA":"1","classB":"1.2"},
	"Photosynthesis - antenna proteins":{"classA":"1","classB":"1.2"},
	"Carbon fixation in photosynthetic organisms":{"classA":"1","classB":"1.2"},
	"Carbon fixation pathways in prokaryotes":{"classA":"1","classB":"1.2"},
	"Methane metabolism":{"classA":"1","classB":"1.2"},
	"Nitrogen metabolism":{"classA":"1","classB":"1.2"},
	"Sulfur metabolism":{"classA":"1","classB":"1.2"},
	"Fatty acid biosynthesis":{"classA":"1","classB":"1.3"},
	"Fatty acid elongation":{"classA":"1","classB":"1.3"},
	"Fatty acid degradation":{"classA":"1","classB":"1.3"},
	"Synthesis and degradation of ketone bodies":{"classA":"1","classB":"1.3"},
	"Cutin, suberine and wax biosynthesis":{"classA":"1","classB":"1.3"},
	"Steroid biosynthesis":{"classA":"1","classB":"1.3"},
	"Primary bile acid biosynthesis":{"classA":"1","classB":"1.3"},
	"Secondary bile acid biosynthesis":{"classA":"1","classB":"1.3"},
	"Steroid hormone biosynthesis":{"classA":"1","classB":"1.3"},
	"Glycerolipid metabolism":{"classA":"1","classB":"1.3"},
	"Glycerophospholipid metabolism":{"classA":"1","classB":"1.3"},
	"Ether lipid metabolism":{"classA":"1","classB":"1.3"},
	"Sphingolipid metabolism":{"classA":"1","classB":"1.3"},
	"Arachidonic acid metabolism":{"classA":"1","classB":"1.3"},
	"Linoleic acid metabolism":{"classA":"1","classB":"1.3"},
	"alpha-Linolenic acid metabolism":{"classA":"1","classB":"1.3"},
	"Biosynthesis of unsaturated fatty acids":{"classA":"1","classB":"1.3"},
	"Purine metabolism":{"classA":"1","classB":"1.4"},
	"Pyrimidine metabolism":{"classA":"1","classB":"1.4"},
	"Alanine, aspartate and glutamate metabolism":{"classA":"1","classB":"1.5"},
	"Glycine, serine and threonine metabolism":{"classA":"1","classB":"1.5"},
	"Cysteine and methionine metabolism":{"classA":"1","classB":"1.5"},
	"Valine, leucine and isoleucine degradation":{"classA":"1","classB":"1.5"},
	"Valine, leucine and isoleucine biosynthesis":{"classA":"1","classB":"1.5"},
	"Lysine biosynthesis":{"classA":"1","classB":"1.5"},
	"Lysine degradation":{"classA":"1","classB":"1.5"},
	"Arginine and proline metabolism":{"classA":"1","classB":"1.5"},
	"Histidine metabolism":{"classA":"1","classB":"1.5"},
	"Tyrosine metabolism":{"classA":"1","classB":"1.5"},
	"Phenylalanine metabolism":{"classA":"1","classB":"1.5"},
	"Tryptophan metabolism":{"classA":"1","classB":"1.5"},
	"Phenylalanine, tyrosine and tryptophan biosynthesis":{"classA":"1","classB":"1.5"},
	"beta-Alanine metabolism":{"classA":"1","classB":"1.6"},
	"Taurine and hypotaurine metabolism":{"classA":"1","classB":"1.6"},
	"Phosphonate and phosphinate metabolism":{"classA":"1","classB":"1.6"},
	"Selenocompound metabolism":{"classA":"1","classB":"1.6"},
	"Cyanoamino acid metabolism":{"classA":"1","classB":"1.6"},
	"D-Glutamine and D-glutamate metabolism":{"classA":"1","classB":"1.6"},
	"D-Arginine and D-ornithine metabolism":{"classA":"1","classB":"1.6"},
	"D-Alanine metabolism":{"classA":"1","classB":"1.6"},
	"Glutathione metabolism":{"classA":"1","classB":"1.6"},
	"N-Glycan biosynthesis":{"classA":"1","classB":"1.7"},
	"Various types of N-glycan biosynthesis":{"classA":"1","classB":"1.7"},
	"Mucin type O-Glycan biosynthesis":{"classA":"1","classB":"1.7"},
	"Other types of O-glycan biosynthesis":{"classA":"1","classB":"1.7"},
	"Glycosaminoglycan biosynthesis - CS/DS":{"classA":"1","classB":"1.7"},
	"Glycosaminoglycan biosynthesis - HS/Hep":{"classA":"1","classB":"1.7"},
	"Glycosaminoglycan biosynthesis - KS":{"classA":"1","classB":"1.7"},
	"Glycosaminoglycan degradation":{"classA":"1","classB":"1.7"},
	"Glycosylphosphatidylinositol(GPI)-anchor biosynthesis":{"classA":"1","classB":"1.7"},
	"Glycosphingolipid biosynthesis - lacto and neolacto series":{"classA":"1","classB":"1.7"},
	"Glycosphingolipid biosynthesis - globo series":{"classA":"1","classB":"1.7"},
	"Glycosphingolipid biosynthesis - ganglio series":{"classA":"1","classB":"1.7"},
	"Lipopolysaccharide biosynthesis":{"classA":"1","classB":"1.7"},
	"Peptidoglycan biosynthesis":{"classA":"1","classB":"1.7"},
	"Other glycan degradation":{"classA":"1","classB":"1.7"},
	"Thiamine metabolism":{"classA":"1","classB":"1.8"},
	"Riboflavin metabolism":{"classA":"1","classB":"1.8"},
	"Vitamin B6 metabolism":{"classA":"1","classB":"1.8"},
	"Nicotinate and nicotinamide metabolism":{"classA":"1","classB":"1.8"},
	"Pantothenate and CoA biosynthesis":{"classA":"1","classB":"1.8"},
	"Biotin metabolism":{"classA":"1","classB":"1.8"},
	"Lipoic acid metabolism":{"classA":"1","classB":"1.8"},
	"Folate biosynthesis":{"classA":"1","classB":"1.8"},
	"One carbon pool by folate":{"classA":"1","classB":"1.8"},
	"Retinol metabolism":{"classA":"1","classB":"1.8"},
	"Porphyrin and chlorophyll metabolism":{"classA":"1","classB":"1.8"},
	"Ubiquinone and other terpenoid-quinone biosynthesis":{"classA":"1","classB":"1.8"},
	"Terpenoid backbone biosynthesis":{"classA":"1","classB":"1.9"},
	"Monoterpenoid biosynthesis":{"classA":"1","classB":"1.9"},
	"Sesquiterpenoid and triterpenoid biosynthesis":{"classA":"1","classB":"1.9"},
	"Diterpenoid biosynthesis":{"classA":"1","classB":"1.9"},
	"Carotenoid biosynthesis":{"classA":"1","classB":"1.9"},
	"Brassinosteroid biosynthesis":{"classA":"1","classB":"1.9"},
	"Insect hormone biosynthesis":{"classA":"1","classB":"1.9"},
	"Zeatin biosynthesis":{"classA":"1","classB":"1.9"},
	"Limonene and pinene degradation":{"classA":"1","classB":"1.9"},
	"Geraniol degradation":{"classA":"1","classB":"1.9"},
	"Type I polyketide structures":{"classA":"1","classB":"1.9"},
	"Biosynthesis of 12-, 14- and 16-membered macrolides":{"classA":"1","classB":"1.9"},
	"Biosynthesis of ansamycins":{"classA":"1","classB":"1.9"},
	"Biosynthesis of type II polyketide backbone":{"classA":"1","classB":"1.9"},
	"Biosynthesis of type II polyketide products":{"classA":"1","classB":"1.9"},
	"Tetracycline biosynthesis":{"classA":"1","classB":"1.9"},
	"Polyketide sugar unit biosynthesis":{"classA":"1","classB":"1.9"},
	"Nonribosomal peptide structures":{"classA":"1","classB":"1.9"},
	"Biosynthesis of siderophore group nonribosomal peptides":{"classA":"1","classB":"1.9"},
	"Biosynthesis of vancomycin group antibiotics":{"classA":"1","classB":"1.9"},
	"Phenylpropanoid biosynthesis":{"classA":"1","classB":"1.10"},
	"Stilbenoid, diarylheptanoid and gingerol biosynthesis":{"classA":"1","classB":"1.10"},
	"Flavonoid biosynthesis":{"classA":"1","classB":"1.10"},
	"Flavone and flavonol biosynthesis":{"classA":"1","classB":"1.10"},
	"Anthocyanin biosynthesis":{"classA":"1","classB":"1.10"},
	"Isoflavonoid biosynthesis":{"classA":"1","classB":"1.10"},
	"Indole alkaloid biosynthesis":{"classA":"1","classB":"1.10"},
	"Indole diterpene alkaloid biosynthesis":{"classA":"1","classB":"1.10"},
	"Isoquinoline alkaloid biosynthesis":{"classA":"1","classB":"1.10"},
	"Tropane, piperidine and pyridine alkaloid biosynthesis":{"classA":"1","classB":"1.10"},
	"Acridone alkaloid biosynthesis":{"classA":"1","classB":"1.10"},
	"Caffeine metabolism":{"classA":"1","classB":"1.10"},
	"Betalain biosynthesis":{"classA":"1","classB":"1.10"},
	"Glucosinolate biosynthesis":{"classA":"1","classB":"1.10"},
	"Benzoxazinoid biosynthesis":{"classA":"1","classB":"1.10"},
	"Penicillin and cephalosporin biosynthesis":{"classA":"1","classB":"1.10"},
	"Carbapenem biosynthesis":{"classA":"1","classB":"1.10"},
	"Clavulanic acid biosynthesis":{"classA":"1","classB":"1.10"},
	"Streptomycin biosynthesis":{"classA":"1","classB":"1.10"},
	"Butirosin and neomycin biosynthesis":{"classA":"1","classB":"1.10"},
	"Puromycin biosynthesis":{"classA":"1","classB":"1.10"},
	"Novobiocin biosynthesis":{"classA":"1","classB":"1.10"},
	"Aflatoxin biosynthesis":{"classA":"1","classB":"1.10"},
	"Benzoate degradation":{"classA":"1","classB":"1.11"},
	"Aminobenzoate degradation":{"classA":"1","classB":"1.11"},
	"Fluorobenzoate degradation":{"classA":"1","classB":"1.11"},
	"Chloroalkane and chloroalkene degradation":{"classA":"1","classB":"1.11"},
	"Chlorocyclohexane and chlorobenzene degradation":{"classA":"1","classB":"1.11"},
	"Toluene degradation":{"classA":"1","classB":"1.11"},
	"Xylene degradation":{"classA":"1","classB":"1.11"},
	"Nitrotoluene degradation":{"classA":"1","classB":"1.11"},
	"Ethylbenzene degradation":{"classA":"1","classB":"1.11"},
	"Styrene degradation":{"classA":"1","classB":"1.11"},
	"Atrazine degradation":{"classA":"1","classB":"1.11"},
	"Caprolactam degradation":{"classA":"1","classB":"1.11"},
	"DDT degradation":{"classA":"1","classB":"1.11"},
	"Bisphenol degradation":{"classA":"1","classB":"1.11"},
	"Dioxin degradation":{"classA":"1","classB":"1.11"},
	"Naphthalene degradation":{"classA":"1","classB":"1.11"},
	"Polycyclic aromatic hydrocarbon degradation":{"classA":"1","classB":"1.11"},
	"Furfural degradation":{"classA":"1","classB":"1.11"},
	"Steroid degradation":{"classA":"1","classB":"1.11"},
	"Metabolism of xenobiotics by cytochrome P450":{"classA":"1","classB":"1.11"},
	"Drug metabolism - cytochrome P450":{"classA":"1","classB":"1.11"},
	"Drug metabolism - other enzymes":{"classA":"1","classB":"1.11"},
	"Overview of biosynthetic pathways":{"classA":"1","classB":"1.12"},
	"Biosynthesis of plant secondary metabolites":{"classA":"1","classB":"1.12"},
	"Biosynthesis of phenylpropanoids":{"classA":"1","classB":"1.12"},
	"Biosynthesis of terpenoids and steroids":{"classA":"1","classB":"1.12"},
	"Biosynthesis of alkaloids derived from shikimate pathway":{"classA":"1","classB":"1.12"},
	"Biosynthesis of alkaloids derived from ornithine, lysine and nicotinic acid":{"classA":"1","classB":"1.12"},
	"Biosynthesis of alkaloids derived from histidine and purine":{"classA":"1","classB":"1.12"},
	"Biosynthesis of alkaloids derived from terpenoid and polyketide":{"classA":"1","classB":"1.12"},
	"Biosynthesis of plant hormones":{"classA":"1","classB":"1.12"},
	"RNA polymerase":{"classA":"2","classB":"2.1"},
	"Basal transcription factors":{"classA":"2","classB":"2.1"},
	"Spliceosome":{"classA":"2","classB":"2.1"},
	"Ribosome":{"classA":"2","classB":"2.2"},
	"Aminoacyl-tRNA biosynthesis":{"classA":"2","classB":"2.2"},
	"RNA transport":{"classA":"2","classB":"2.2"},
	"mRNA surveillance pathway":{"classA":"2","classB":"2.2"},
	"Ribosome biogenesis in eukaryotes":{"classA":"2","classB":"2.2"},
	"Protein export":{"classA":"2","classB":"2.3"},
	"Protein processing in endoplasmic reticulum":{"classA":"2","classB":"2.3"},
	"SNARE interactions in vesicular transport":{"classA":"2","classB":"2.3"},
	"Ubiquitin mediated proteolysis":{"classA":"2","classB":"2.3"},
	"Sulfur relay system":{"classA":"2","classB":"2.3"},
	"Proteasome":{"classA":"2","classB":"2.3"},
	"RNA degradation":{"classA":"2","classB":"2.3"},
	"DNA replication":{"classA":"2","classB":"2.4"},
	"Base excision repair":{"classA":"2","classB":"2.4"},
	"Nucleotide excision repair":{"classA":"2","classB":"2.4"},
	"Mismatch repair":{"classA":"2","classB":"2.4"},
	"Homologous recombination":{"classA":"2","classB":"2.4"},
	"Non-homologous end-joining":{"classA":"2","classB":"2.4"},
	"Fanconi anemia pathway":{"classA":"2","classB":"2.4"},
	"ABC transporters":{"classA":"3","classB":"3.1"},
	"Phosphotransferase system (PTS)":{"classA":"3","classB":"3.1"},
	"Bacterial secretion system":{"classA":"3","classB":"3.1"},
	"Two-component system":{"classA":"3","classB":"3.2"},
	"Ras signaling pathway":{"classA":"3","classB":"3.2"},
	"Rap1 signaling pathway":{"classA":"3","classB":"3.2"},
	"MAPK signaling pathway":{"classA":"3","classB":"3.2"},
	"MAPK signaling pathway - fly":{"classA":"3","classB":"3.2"},
	"MAPK signaling pathway - yeast":{"classA":"3","classB":"3.2"},
	"ErbB signaling pathway":{"classA":"3","classB":"3.2"},
	"Wnt signaling pathway":{"classA":"3","classB":"3.2"},
	"Notch signaling pathway":{"classA":"3","classB":"3.2"},
	"Hedgehog signaling pathway":{"classA":"3","classB":"3.2"},
	"TGF-beta signaling pathway":{"classA":"3","classB":"3.2"},
	"Hippo signaling pathway":{"classA":"3","classB":"3.2"},
	"Hippo signaling pathway - fly":{"classA":"3","classB":"3.2"},
	"VEGF signaling pathway":{"classA":"3","classB":"3.2"},
	"Jak-STAT signaling pathway":{"classA":"3","classB":"3.2"},
	"NF-kappa B signaling pathway":{"classA":"3","classB":"3.2"},
	"TNF signaling pathway":{"classA":"3","classB":"3.2"},
	"HIF-1 signaling pathway":{"classA":"3","classB":"3.2"},
	"FoxO signaling pathway":{"classA":"3","classB":"3.2"},
	"Calcium signaling pathway":{"classA":"3","classB":"3.2"},
	"Phosphatidylinositol signaling system":{"classA":"3","classB":"3.2"},
	"Sphingolipid signaling pathway":{"classA":"3","classB":"3.2"},
	"cAMP signaling pathway":{"classA":"3","classB":"3.2"},
	"cGMP-PKG signaling pathway":{"classA":"3","classB":"3.2"},
	"PI3K-Akt signaling pathway":{"classA":"3","classB":"3.2"},
	"AMPK signaling pathway":{"classA":"3","classB":"3.2"},
	"mTOR signaling pathway":{"classA":"3","classB":"3.2"},
	"Plant hormone signal transduction":{"classA":"3","classB":"3.2"},
	"Neuroactive ligand-receptor interaction":{"classA":"3","classB":"3.3"},
	"Cytokine-cytokine receptor interaction":{"classA":"3","classB":"3.3"},
	"ECM-receptor interaction":{"classA":"3","classB":"3.3"},
	"Cell adhesion molecules (CAMs)":{"classA":"3","classB":"3.3"},
	"Endocytosis":{"classA":"4","classB":"4.1"},
	"Phagosome":{"classA":"4","classB":"4.1"},
	"Lysosome":{"classA":"4","classB":"4.1"},
	"Peroxisome":{"classA":"4","classB":"4.1"},
	"Regulation of autophagy":{"classA":"4","classB":"4.1"},
	"Bacterial chemotaxis":{"classA":"4","classB":"4.2"},
	"Flagellar assembly":{"classA":"4","classB":"4.2"},
	"Regulation of actin cytoskeleton":{"classA":"4","classB":"4.2"},
	"Cell cycle":{"classA":"4","classB":"4.3"},
	"Cell cycle - yeast":{"classA":"4","classB":"4.3"},
	"Cell cycle - Caulobacter":{"classA":"4","classB":"4.3"},
	"Meiosis - yeast":{"classA":"4","classB":"4.3"},
	"Oocyte meiosis":{"classA":"4","classB":"4.3"},
	"Apoptosis":{"classA":"4","classB":"4.3"},
	"p53 signaling pathway":{"classA":"4","classB":"4.3"},
	"Focal adhesion":{"classA":"4","classB":"4.4"},
	"Adherens junction":{"classA":"4","classB":"4.4"},
	"Tight junction":{"classA":"4","classB":"4.4"},
	"Gap junction":{"classA":"4","classB":"4.4"},
	"Signaling pathways regulating pluripotency of stem cells":{"classA":"4","classB":"4.4"},
	"Hematopoietic cell lineage":{"classA":"5","classB":"5.1"},
	"Complement and coagulation cascades":{"classA":"5","classB":"5.1"},
	"Platelet activation":{"classA":"5","classB":"5.1"},
	"Toll-like receptor signaling pathway":{"classA":"5","classB":"5.1"},
	"NOD-like receptor signaling pathway":{"classA":"5","classB":"5.1"},
	"RIG-I-like receptor signaling pathway":{"classA":"5","classB":"5.1"},
	"Cytosolic DNA-sensing pathway":{"classA":"5","classB":"5.1"},
	"Natural killer cell mediated cytotoxicity":{"classA":"5","classB":"5.1"},
	"Antigen processing and presentation":{"classA":"5","classB":"5.1"},
	"T cell receptor signaling pathway":{"classA":"5","classB":"5.1"},
	"B cell receptor signaling pathway":{"classA":"5","classB":"5.1"},
	"Fc epsilon RI signaling pathway":{"classA":"5","classB":"5.1"},
	"Fc gamma R-mediated phagocytosis":{"classA":"5","classB":"5.1"},
	"Leukocyte transendothelial migration":{"classA":"5","classB":"5.1"},
	"Intestinal immune network for IgA production":{"classA":"5","classB":"5.1"},
	"Chemokine signaling pathway":{"classA":"5","classB":"5.1"},
	"Insulin secretion":{"classA":"5","classB":"5.2"},
	"Insulin signaling pathway":{"classA":"5","classB":"5.2"},
	"Glucagon signaling pathway":{"classA":"5","classB":"5.2"},
	"Adipocytokine signaling pathway":{"classA":"5","classB":"5.2"},
	"PPAR signaling pathway":{"classA":"5","classB":"5.2"},
	"GnRH signaling pathway":{"classA":"5","classB":"5.2"},
	"Ovarian steroidogenesis":{"classA":"5","classB":"5.2"},
	"Estrogen signaling pathway":{"classA":"5","classB":"5.2"},
	"Progesterone-mediated oocyte maturation":{"classA":"5","classB":"5.2"},
	"Prolactin signaling pathway":{"classA":"5","classB":"5.2"},
	"Oxytocin signaling pathway":{"classA":"5","classB":"5.2"},
	"Thyroid hormone synthesis":{"classA":"5","classB":"5.2"},
	"Thyroid hormone signaling pathway":{"classA":"5","classB":"5.2"},
	"Melanogenesis":{"classA":"5","classB":"5.2"},
	"Renin-angiotensin system":{"classA":"5","classB":"5.2"},
	"Cardiac muscle contraction":{"classA":"5","classB":"5.3"},
	"Adrenergic signaling in cardiomyocytes":{"classA":"5","classB":"5.3"},
	"Vascular smooth muscle contraction":{"classA":"5","classB":"5.3"},
	"Salivary secretion":{"classA":"5","classB":"5.4"},
	"Gastric acid secretion":{"classA":"5","classB":"5.4"},
	"Pancreatic secretion":{"classA":"5","classB":"5.4"},
	"Bile secretion":{"classA":"5","classB":"5.4"},
	"Carbohydrate digestion and absorption":{"classA":"5","classB":"5.4"},
	"Protein digestion and absorption":{"classA":"5","classB":"5.4"},
	"Fat digestion and absorption":{"classA":"5","classB":"5.4"},
	"Vitamin digestion and absorption":{"classA":"5","classB":"5.4"},
	"Mineral absorption":{"classA":"5","classB":"5.4"},
	"Vasopressin-regulated water reabsorption":{"classA":"5","classB":"5.5"},
	"Aldosterone-regulated sodium reabsorption":{"classA":"5","classB":"5.5"},
	"Endocrine and other factor-regulated calcium reabsorption":{"classA":"5","classB":"5.5"},
	"Proximal tubule bicarbonate reclamation":{"classA":"5","classB":"5.5"},
	"Collecting duct acid secretion":{"classA":"5","classB":"5.5"},
	"Glutamatergic synapse":{"classA":"5","classB":"5.6"},
	"GABAergic synapse":{"classA":"5","classB":"5.6"},
	"Cholinergic synapse":{"classA":"5","classB":"5.6"},
	"Dopaminergic synapse":{"classA":"5","classB":"5.6"},
	"Serotonergic synapse":{"classA":"5","classB":"5.6"},
	"Long-term potentiation":{"classA":"5","classB":"5.6"},
	"Long-term depression":{"classA":"5","classB":"5.6"},
	"Retrograde endocannabinoid signaling":{"classA":"5","classB":"5.6"},
	"Synaptic vesicle cycle":{"classA":"5","classB":"5.6"},
	"Neurotrophin signaling pathway":{"classA":"5","classB":"5.6"},
	"Phototransduction":{"classA":"5","classB":"5.7"},
	"Phototransduction - fly":{"classA":"5","classB":"5.7"},
	"Olfactory transduction":{"classA":"5","classB":"5.7"},
	"Taste transduction":{"classA":"5","classB":"5.7"},
	"Inflammatory mediator regulation of TRP channels":{"classA":"5","classB":"5.7"},
	"Dorso-ventral axis formation":{"classA":"5","classB":"5.8"},
	"Axon guidance":{"classA":"5","classB":"5.8"},
	"Osteoclast differentiation":{"classA":"5","classB":"5.8"},
	"Circadian rhythm":{"classA":"5","classB":"5.9"},
	"Circadian entrainment":{"classA":"5","classB":"5.9"},
	"Circadian rhythm - fly":{"classA":"5","classB":"5.9"},
	"Circadian rhythm - plant":{"classA":"5","classB":"5.9"},
	"Plant-pathogen interaction":{"classA":"5","classB":"5.9"},
	"Pathways in cancer":{"classA":"6","classB":"6.1"},
	"Central carbon metabolism in cancer":{"classA":"6","classB":"6.1"},
	"Choline metabolism in cancer":{"classA":"6","classB":"6.1"},
	"Transcriptional misregulation in cancer":{"classA":"6","classB":"6.1"},
	"MicroRNAs in cancer":{"classA":"6","classB":"6.1"},
	"Proteoglycans in cancer":{"classA":"6","classB":"6.1"},
	"Chemical carcinogenesis":{"classA":"6","classB":"6.1"},
	"Viral carcinogenesis":{"classA":"6","classB":"6.1"},
	"Colorectal cancer":{"classA":"6","classB":"6.2"},
	"Pancreatic cancer":{"classA":"6","classB":"6.2"},
	"Glioma":{"classA":"6","classB":"6.2"},
	"Thyroid cancer":{"classA":"6","classB":"6.2"},
	"Acute myeloid leukemia":{"classA":"6","classB":"6.2"},
	"Chronic myeloid leukemia":{"classA":"6","classB":"6.2"},
	"Basal cell carcinoma":{"classA":"6","classB":"6.2"},
	"Melanoma":{"classA":"6","classB":"6.2"},
	"Renal cell carcinoma":{"classA":"6","classB":"6.2"},
	"Bladder cancer":{"classA":"6","classB":"6.2"},
	"Prostate cancer":{"classA":"6","classB":"6.2"},
	"Endometrial cancer":{"classA":"6","classB":"6.2"},
	"Small cell lung cancer":{"classA":"6","classB":"6.2"},
	"Non-small cell lung cancer":{"classA":"6","classB":"6.2"},
	"Asthma":{"classA":"6","classB":"6.3"},
	"Systemic lupus erythematosus":{"classA":"6","classB":"6.3"},
	"Rheumatoid arthritis":{"classA":"6","classB":"6.3"},
	"Autoimmune thyroid disease":{"classA":"6","classB":"6.3"},
	"Inflammatory bowel disease (IBD)":{"classA":"6","classB":"6.3"},
	"Allograft rejection":{"classA":"6","classB":"6.3"},
	"Graft-versus-host disease":{"classA":"6","classB":"6.3"},
	"Primary immunodeficiency":{"classA":"6","classB":"6.3"},
	"Alzheimer's disease":{"classA":"6","classB":"6.4"},
	"Parkinson's disease":{"classA":"6","classB":"6.4"},
	"Amyotrophic lateral sclerosis (ALS)":{"classA":"6","classB":"6.4"},
	"Huntington's disease":{"classA":"6","classB":"6.4"},
	"Prion diseases":{"classA":"6","classB":"6.4"},
	"Cocaine addiction":{"classA":"6","classB":"6.5"},
	"Amphetamine addiction":{"classA":"6","classB":"6.5"},
	"Morphine addiction":{"classA":"6","classB":"6.5"},
	"Nicotine addiction":{"classA":"6","classB":"6.5"},
	"Alcoholism":{"classA":"6","classB":"6.5"},
	"Hypertrophic cardiomyopathy (HCM)":{"classA":"6","classB":"6.6"},
	"Arrhythmogenic right ventricular cardiomyopathy (ARVC)":{"classA":"6","classB":"6.6"},
	"Dilated cardiomyopathy (DCM)":{"classA":"6","classB":"6.6"},
	"Viral myocarditis":{"classA":"6","classB":"6.6"},
	"Type I diabetes mellitus":{"classA":"6","classB":"6.7"},
	"Type II diabetes mellitus":{"classA":"6","classB":"6.7"},
	"Non-alcoholic fatty liver disease (NAFLD)":{"classA":"6","classB":"6.7"},
	"Maturity onset diabetes of the young":{"classA":"6","classB":"6.7"},
	"Vibrio cholerae infection":{"classA":"6","classB":"6.8"},
	"Vibrio cholerae pathogenic cycle":{"classA":"6","classB":"6.8"},
	"Epithelial cell signaling in Helicobacter pylori infection":{"classA":"6","classB":"6.8"},
	"Pathogenic Escherichia coli infection":{"classA":"6","classB":"6.8"},
	"Salmonella infection":{"classA":"6","classB":"6.8"},
	"Shigellosis":{"classA":"6","classB":"6.8"},
	"Pertussis":{"classA":"6","classB":"6.8"},
	"Legionellosis":{"classA":"6","classB":"6.8"},
	"Staphylococcus aureus infection":{"classA":"6","classB":"6.8"},
	"Tuberculosis":{"classA":"6","classB":"6.8"},
	"Bacterial invasion of epithelial cells":{"classA":"6","classB":"6.8"},
	"HTLV-I infection":{"classA":"6","classB":"6.9"},
	"Measles":{"classA":"6","classB":"6.9"},
	"Influenza A":{"classA":"6","classB":"6.9"},
	"Hepatitis B":{"classA":"6","classB":"6.9"},
	"Hepatitis C":{"classA":"6","classB":"6.9"},
	"Herpes simplex infection":{"classA":"6","classB":"6.9"},
	"Epstein-Barr virus infection":{"classA":"6","classB":"6.9"},
	"Amoebiasis":{"classA":"6","classB":"6.10"},
	"Malaria":{"classA":"6","classB":"6.10"},
	"Toxoplasmosis":{"classA":"6","classB":"6.10"},
	"Leishmaniasis":{"classA":"6","classB":"6.10"},
	"Chagas disease (American trypanosomiasis)":{"classA":"6","classB":"6.10"},
	"African trypanosomiasis":{"classA":"6","classB":"6.10"},
	"beta-Lactam resistance":{"classA":"6","classB":"6.11"},
	"Vancomycin resistance":{"classA":"6","classB":"6.11"},
	"Penicillins":{"classA":"7","classB":"7.1"},
	"Cephalosporins - parenteral agents":{"classA":"7","classB":"7.1"},
	"Cephalosporins - oral agents":{"classA":"7","classB":"7.1"},
	"Aminoglycosides":{"classA":"7","classB":"7.1"},
	"Tetracyclines":{"classA":"7","classB":"7.1"},
	"Macrolides and ketolides":{"classA":"7","classB":"7.1"},
	"Quinolones":{"classA":"7","classB":"7.1"},
	"Rifamycins":{"classA":"7","classB":"7.1"},
	"Antifungal agents":{"classA":"7","classB":"7.1"},
	"Antiviral agents":{"classA":"7","classB":"7.1"},
	"Anti-HIV agents":{"classA":"7","classB":"7.1"},
	"Antineoplastics - alkylating agents":{"classA":"7","classB":"7.2"},
	"Antineoplastics - antimetabolic agents":{"classA":"7","classB":"7.2"},
	"Antineoplastics - agents from natural products":{"classA":"7","classB":"7.2"},
	"Antineoplastics - hormones":{"classA":"7","classB":"7.2"},
	"Antineoplastics - protein kinases inhibitors":{"classA":"7","classB":"7.2"},
	"Hypnotics":{"classA":"7","classB":"7.3"},
	"Anxiolytics":{"classA":"7","classB":"7.3"},
	"Anticonvulsants":{"classA":"7","classB":"7.3"},
	"Local analgesics":{"classA":"7","classB":"7.3"},
	"Opioid analgesics":{"classA":"7","classB":"7.3"},
	"Antipsychotics":{"classA":"7","classB":"7.3"},
	"Antipsychotics - phenothiazines":{"classA":"7","classB":"7.3"},
	"Antipsychotics - butyrophenones":{"classA":"7","classB":"7.3"},
	"Antidepressants":{"classA":"7","classB":"7.3"},
	"Agents for Alzheimer-type dementia":{"classA":"7","classB":"7.3"},
	"Antiparkinsonian agents":{"classA":"7","classB":"7.3"},
	"Sulfonamide derivatives - overview":{"classA":"7","classB":"7.4"},
	"Sulfonamide derivatives - sulfa drugs":{"classA":"7","classB":"7.4"},
	"Sulfonamide derivatives - diuretics":{"classA":"7","classB":"7.4"},
	"Sulfonamide derivatives - hypoglycemic agents":{"classA":"7","classB":"7.4"},
	"Antiarrhythmic drugs":{"classA":"7","classB":"7.4"},
	"Antiulcer drugs":{"classA":"7","classB":"7.4"},
	"Immunosuppressive agents":{"classA":"7","classB":"7.4"},
	"Osteoporosis drugs":{"classA":"7","classB":"7.4"},
	"Antimigraines":{"classA":"7","classB":"7.4"},
	"Antithrombosis agents":{"classA":"7","classB":"7.4"},
	"Antirheumatics - DMARDs and biological agents":{"classA":"7","classB":"7.4"},
	"Antidiabetics":{"classA":"7","classB":"7.4"},
	"Antidyslipidemic agents":{"classA":"7","classB":"7.4"},
	"Antiglaucoma agents":{"classA":"7","classB":"7.4"},
	"Cholinergic and anticholinergic drugs":{"classA":"7","classB":"7.5"},
	"alpha-Adrenergic receptor agonists/antagonists":{"classA":"7","classB":"7.5"},
	"beta-Adrenergic receptor agonists/antagonists":{"classA":"7","classB":"7.5"},
	"Dopamine receptor agonists/antagonists":{"classA":"7","classB":"7.5"},
	"Histamine H1 receptor antagonists":{"classA":"7","classB":"7.5"},
	"Histamine H2/H3 receptor agonists/antagonists":{"classA":"7","classB":"7.5"},
	"Serotonin receptor agonists/antagonists":{"classA":"7","classB":"7.5"},
	"Eicosanoid receptor agonists/antagonists":{"classA":"7","classB":"7.5"},
	"Opioid receptor agonists/antagonists":{"classA":"7","classB":"7.5"},
	"Angiotensin receptor and endothelin receptor antagonists":{"classA":"7","classB":"7.5"},
	"Glucocorticoid and mineralocorticoid receptor agonists/antagonists":{"classA":"7","classB":"7.6"},
	"Progesterone, androgen and estrogen receptor agonists/antagonists":{"classA":"7","classB":"7.6"},
	"Retinoic acid receptor (RAR) and retinoid X receptor (RXR) agonists/antagonists":{"classA":"7","classB":"7.6"},
	"Peroxisome proliferator-activated receptor (PPAR) agonists":{"classA":"7","classB":"7.6"},
	"Nicotinic cholinergic receptor antagonists":{"classA":"7","classB":"7.7"},
	"GABA-A receptor agonists/antagonists":{"classA":"7","classB":"7.7"},
	"Calcium channel blocking drugs":{"classA":"7","classB":"7.7"},
	"Sodium channel blocking drugs":{"classA":"7","classB":"7.7"},
	"Potassium channel blocking and opening drugs":{"classA":"7","classB":"7.7"},
	"N-Metyl-D-aspartic acid receptor antagonists":{"classA":"7","classB":"7.7"},
	"Ion transporter inhibitors":{"classA":"7","classB":"7.8"},
	"Neurotransmitter transporter inhibitors":{"classA":"7","classB":"7.8"},
	"Catecholamine transferase inhibitors":{"classA":"7","classB":"7.9"},
	"Cyclooxygenase inhibitors":{"classA":"7","classB":"7.9"},
	"HMG-CoA reductase inhibitors":{"classA":"7","classB":"7.9"},
	"Renin-angiotensin system inhibitors":{"classA":"7","classB":"7.9"},
	"HIV protease inhibitors":{"classA":"7","classB":"7.9"},
	"Quinolines":{"classA":"7","classB":"7.10"},
	"Eicosanoids":{"classA":"7","classB":"7.10"},
	"Prostaglandins":{"classA":"7","classB":"7.10"},
	"Benzoic acid family":{"classA":"7","classB":"7.11"},
	"1,2-Diphenyl substitution family":{"classA":"7","classB":"7.11"},
	"Naphthalene family":{"classA":"7","classB":"7.11"},
	"Benzodiazepine family":{"classA":"7","classB":"7.11"},
}
var keggclassAname={
	"1":"Metabolism",
	"2":"Genetic Information Processing",
	"3":"Environmental Information Processing",
	"4":"Cellular Processes",
	"5":"Organismal Systems",
	"6":"Human Diseases",
	"7":"Drug Development",
	"8":"Other and unknow"
}
var keggclassBname={
	"1.0":"Global and overview maps",
	"1.1":"Carbohydrate metabolism",
	"1.2":"Energy metabolism",
	"1.3":"Lipid metabolism",
	"1.4":"Nucleotide metabolism",
	"1.5":"Amino acid metabolism",
	"1.6":"Metabolism of other amino acids",
	"1.7":"Glycan biosynthesis and metabolism",
	"1.8":"Metabolism of cofactors and vitamins",
	"1.9":"Metabolism of terpenoids and polyketides",
	"1.10":"Biosynthesis of other secondary metabolites",
	"1.11":"Xenobiotics biodegradation and metabolism",
	"1.12":"Chemical structure transformation maps",
	"2.1":"Transcription",
	"2.2":"Translation",
	"2.3":"Folding, sorting and degradation",
	"2.4":"Replication and repair",
	"3.1":"Membrane transport",
	"3.2":"Signal transduction",
	"3.3":"Signaling molecules and interaction",
	"4.1":"Transport and catabolism",
	"4.2":"Cell motility",
	"4.3":"Cell growth and death",
	"4.4":"Cellular community",
	"5.1":"Immune system",
	"5.2":"Endocrine system",
	"5.3":"Circulatory system",
	"5.4":"Digestive system",
	"5.5":"Excretory system",
	"5.6":"Nervous system",
	"5.7":"Sensory system",
	"5.8":"Development",
	"5.9":"Environmental adaptation",
	"6.1":"Cancers: Overview",
	"6.2":"Cancers: Specific types",
	"6.3":"Immune diseases",
	"6.4":"Neurodegenerative diseases",
	"6.5":"Substance dependence",
	"6.6":"Cardiovascular diseases",
	"6.7":"Endocrine and metabolic diseases",
	"6.8":"Infectious diseases: Bacterial",
	"6.9":"Infectious diseases: Viral",
	"6.10":"Infectious diseases: Parasitic",
	"6.11":"Drug resistance",
	"7.1":"Chronology: Antiinfectives",
	"7.2":"Chronology: Antineoplastics",
	"7.3":"Chronology: Nervous system agents",
	"7.4":"Chronology: Other drugs",
	"7.5":"Target-based classification: G protein-coupled receptors",
	"7.6":"Target-based classification: Nuclear receptors",
	"7.7":"Target-based classification: Ion channels",
	"7.8":"Target-based classification: Transporters",
	"7.9":"Target-based classification: Enzymes",
	"7.10":"Structure-based classification",
	"7.11":"Skeleton-based classification",
	"8.1":"Other and unknow"
}
