
#' A unified method for create node ID
#'
#' @details Create debug data of metaDNA network elongation.
#'    The input seed parameter should have such data structure:
#'    \enumerate{
#'       \item \code{feature} is the ms1 feature ID
#'       \item \code{KEGG} is the kegg compound id that current seed object identified as
#'       \item \code{ref} is the ms2 spectrum matrix reference index value, which should contains two member: \code{file} and \code{scan}
#'    }
#' 
#' @param seed The identified metaDNA seed data. 
#' 
trace.node <- function(seed) {
	sprintf("%s|%s#%s#%s", seed$KEGG, seed$feature, seed$ref$file, seed$ref$scan);
}

#' Network Visualize of the MetaDNA result 
#'
#' @param result The output result data set which is generated by \code{metaDNA} function.
#'
#' 
network.trace <- function(result) {
	infer.routine <- list();
	
	for (cluster in result) {
		if (cluster %=>% IsNothing) {
			next;
		}
		
		for (block in cluster) {
			if (block %=>% IsNothing) {
				next;
			}
			
			for (feature in block) {
				# the trace data is a string vector
				# contains the metaDNA infer routine information
				# we can use this information for create network
				# visualization data.
				#
				# Each node value in this trace vector is in format
				# produced by ``trace.node`` function.
				#
				trace   <- feature$align$trace;
				scores  <- feature$align$score;
				kegg_id <- feature$kegg.info$kegg$ID;
				hit     <- feature$align$ms2.name;
				hit     <- sprintf(
					"%s|%s#%s|%s|%s,%s", 
					feature$name, hit$file, hit$scan, 
					feature$feature$maxinto, 
					scores[1], scores[2]
				);
				
				paralog <- infer.routine[[kegg_id]] %||% list();
				paralog[[hit]] <- trace;
				
				infer.routine[[kegg_id]] <- paralog;
			}
		}
	}
	
	infer.routine;
}

#' Save metaDNA network
#'
#' @details save network data into Xml file.
#'
save.network <- function(infer, outputdir) {
	file <- sprintf("%s/MetaDNA.Xml", outputdir);
	text <- textWriter(file);
	
	out <- XML.Framework(
		write    = text$println,
		do.write = function(write) do.write.network(write, infer),
		rootName = "MetaDNA"
	);
	
	text$close();
}

do.write.network <- function(write, infer) {
	for (kegg_id in names(infer)) {
		trace.cluster <- infer[[kegg_id]];
		
		write('<compound kegg="%s" candidates="%s">', kegg_id, length(trace.cluster));
		
		for (unknown_name in names(trace.cluster)) {
			trace <- trace.cluster[[unknown_name]];
			# `M137T1026|lxy-CID30.mzXML#3380|29188.0625|0.889599165343844,0.821310092994763`
			# id|ms2_index|maxinto|forward,reverse
			unknown_name <- Strings.Split(unknown_name, "\\|");
			align_scores <- Strings.Split(unknown_name[4], ",");
			
			write('<unknown name="%s" Msn="%s" length="%s" intensity="%s" scores="%s">', 
				unknown_name[1], 
				unknown_name[2], 
				length(trace), 
				unknown_name[3], 
				sprintf("%s %s", align_scores[1], align_scores[2])
			);
			
			for(node in trace) {
				node <- Strings.Split(node, "\\|");
				id <- node[1]
				feature <- Strings.Split(node[2], "[#]");
				node <- sprintf("%s#%s", feature[2], feature[3]);
				
				write('<node kegg="%s" ms1="%s">%s</node>', id, feature[1], node);
			}
			
			write('</unknown>');
		}
		
		write("</compound>");
	}
	
	invisible(NULL);
}