
#' A unified method for create node ID
#'
#' @details Create debug data of metaDNA network elongation.
#'    The input seed parameter should have such data structure:
#'    \enumerate{
#'       \item \code{feature} is the ms1 feature ID
#'       \item \code{KEGG} is the kegg compound id that current seed object identified as
#'       \item \code{ref} is the ms2 spectrum matrix reference index value, which should contains two member: \code{file} and \code{scan}
#'    }
#' 
#' @param seed The identified metaDNA seed data. 
#' 
trace.node <- function(seed) {
	sprintf("%s|%s#%s#%s", seed$KEGG, seed$feature, seed$ref$file, seed$ref$scan);
}

#' Network Visualize of the MetaDNA result 
#'
#' @param result The output result data set which is generated by \code{metaDNA} function.
#'
#' 
network.trace <- function(result) {
	infer.routine <- list();
	
	for (cluster in result) {
		if (cluster %=>% IsNothing) {
			next;
		}
		
		for (block in cluster) {
			if (block %=>% IsNothing) {
				next;
			}
			
			for (feature in block) {
				# the trace data is a string vector
				# contains the metaDNA infer routine information
				# we can use this information for create network
				# visualization data.
				#
				# Each node value in this trace vector is in format
				# produced by ``trace.node`` function.
				#
				trace   <- feature$align$trace;
				kegg_id <- feature$kegg.info$kegg$ID;
				hit     <- feature$align$ms2.name;
				hit     <- sprintf("%s|%s#%s", feature$name, hit$file, hit$scan);
				
				paralog <- infer.routine[[kegg_id]] %||% list();
				paralog[[hit]] <- trace;
				
				infer.routine[[kegg_id]] <- paralog;
			}
		}
	}
	
	infer.routine;
}

#' Save metaDNA network
#'
#' @details save network data into Xml file.
#'
save.network <- function(infer, outputdir) {

}