#Region "Microsoft.VisualBasic::86f3e0a25f6f9286acf371f331fdbe5a, metadb\Lipidomics\Resources\Resources.Designer.vb"

    ' Author:
    ' 
    '       xieguigang (gg.xie@bionovogene.com, BioNovoGene Co., LTD.)
    ' 
    ' Copyright (c) 2018 gg.xie@bionovogene.com, BioNovoGene Co., LTD.
    ' 
    ' 
    ' MIT License
    ' 
    ' 
    ' Permission is hereby granted, free of charge, to any person obtaining a copy
    ' of this software and associated documentation files (the "Software"), to deal
    ' in the Software without restriction, including without limitation the rights
    ' to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
    ' copies of the Software, and to permit persons to whom the Software is
    ' furnished to do so, subject to the following conditions:
    ' 
    ' The above copyright notice and this permission notice shall be included in all
    ' copies or substantial portions of the Software.
    ' 
    ' THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
    ' IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
    ' FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
    ' AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
    ' LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
    ' OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
    ' SOFTWARE.



    ' /********************************************************************************/

    ' Summaries:


    ' Code Statistics:

    '   Total Lines: 122
    '    Code Lines: 42 (34.43%)
    ' Comment Lines: 70 (57.38%)
    '    - Xml Docs: 8.57%
    ' 
    '   Blank Lines: 10 (8.20%)
    '     File Size: 5.00 KB


    '     Module Resources
    ' 
    '         Properties: Culture, LbmQueries, LipidClassProperties, ResourceManager
    ' 
    ' 
    ' /********************************************************************************/

#End Region

'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("BioNovoGene.Analytical.MassSpectrometry.Lipidomics.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Class	Adduct	Ion mode	IsSelected
        '''CAR	[M+H]+	Positive	TRUE
        '''LPC	[M+H]+	Positive	TRUE
        '''LPC	[M+Na]+	Positive	TRUE
        '''LPE	[M+H]+	Positive	TRUE
        '''LPS	[M+H]+	Positive	FALSE
        '''LPG	[M+H]+	Positive	FALSE
        '''LPI	[M+H]+	Positive	FALSE
        '''PC	[M+H]+	Positive	TRUE
        '''PC	[M+Na]+	Positive	TRUE
        '''PE	[M+H]+	Positive	TRUE
        '''PE	[M+Na]+	Positive	TRUE
        '''PI	[M+NH4]+	Positive	TRUE
        '''PI	[M+Na]+	Positive	TRUE
        '''PS	[M+H]+	Positive	TRUE
        '''PS	[M+Na]+	Positive	TRUE
        '''#PT	[M+H]+	Positive	FALSE
        '''PG	[M+NH4]+	Positive	TRUE
        '''BMP	[M+NH4]+	Positive	TRUE
        '''HBMP	[M+NH4]+	Positive	 [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property LbmQueries() As String
            Get
                Return ResourceManager.GetString("LbmQueries", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to LbmClass,DisplayName,AcylChain,AlkylChain,SphingoChain,ExtraAcylChain,TotalChain
        '''Undefined,Undefined,,,,,
        '''Others,Others,,,,,
        '''Unknown,Unknown,,,,,
        '''SPLASH,SPLASH,,,,,
        '''FA,FA,1,,,,1
        '''DMEDFA,DMEDFA,1,,,,1
        '''FAHFA,FAHFA,1,,,1,1
        '''DMEDFAHFA,DMEDFAHFA,1,,,1,1
        '''OxFA,FA,1,,,,1
        '''DMEDOxFA,DMEDFA,1,,,,1
        '''CAR,CAR,1,,,,1
        '''NAE,NAE,1,,,,1
        '''NAGly,NAGly,1,,,1,1
        '''NAGlySer,NAGlySer,1,,,1,1
        '''NAOrn,NAOrn,1,,,1,1
        '''NAPhe,NAPhe,1,,,1,1
        '''NATau,NATau,1,,,1,1
        '''NATryA,NATryA,1,,,1,1
        '''NA5HT,NA5HT,1,,,1,1
        '''NAAla,NAAla,1,,,1,1
        '''NAGln,NAGln,1,,,1,1
        '''NALeu,NAL [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property LipidClassProperties() As String
            Get
                Return ResourceManager.GetString("LipidClassProperties", resourceCulture)
            End Get
        End Property
    End Module
End Namespace

