'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("BioNovoGene.Analytical.MassSpectrometry.Lipidomics.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Class	Adduct	Ion mode	IsSelected
        '''CAR	[M+H]+	Positive	TRUE
        '''LPC	[M+H]+	Positive	TRUE
        '''LPC	[M+Na]+	Positive	TRUE
        '''LPE	[M+H]+	Positive	TRUE
        '''LPS	[M+H]+	Positive	FALSE
        '''LPG	[M+H]+	Positive	FALSE
        '''LPI	[M+H]+	Positive	FALSE
        '''PC	[M+H]+	Positive	TRUE
        '''PC	[M+Na]+	Positive	TRUE
        '''PE	[M+H]+	Positive	TRUE
        '''PE	[M+Na]+	Positive	TRUE
        '''PI	[M+NH4]+	Positive	TRUE
        '''PI	[M+Na]+	Positive	TRUE
        '''PS	[M+H]+	Positive	TRUE
        '''PS	[M+Na]+	Positive	TRUE
        '''#PT	[M+H]+	Positive	FALSE
        '''PG	[M+NH4]+	Positive	TRUE
        '''BMP	[M+NH4]+	Positive	TRUE
        '''HBMP	[M+NH4]+	Positive	 [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property LbmQueries() As String
            Get
                Return ResourceManager.GetString("LbmQueries", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to LbmClass,DisplayName,AcylChain,AlkylChain,SphingoChain,ExtraAcylChain,TotalChain
        '''Undefined,Undefined,,,,,
        '''Others,Others,,,,,
        '''Unknown,Unknown,,,,,
        '''SPLASH,SPLASH,,,,,
        '''FA,FA,1,,,,1
        '''DMEDFA,DMEDFA,1,,,,1
        '''FAHFA,FAHFA,1,,,1,1
        '''DMEDFAHFA,DMEDFAHFA,1,,,1,1
        '''OxFA,FA,1,,,,1
        '''DMEDOxFA,DMEDFA,1,,,,1
        '''CAR,CAR,1,,,,1
        '''NAE,NAE,1,,,,1
        '''NAGly,NAGly,1,,,1,1
        '''NAGlySer,NAGlySer,1,,,1,1
        '''NAOrn,NAOrn,1,,,1,1
        '''NAPhe,NAPhe,1,,,1,1
        '''NATau,NATau,1,,,1,1
        '''NATryA,NATryA,1,,,1,1
        '''NA5HT,NA5HT,1,,,1,1
        '''NAAla,NAAla,1,,,1,1
        '''NAGln,NAGln,1,,,1,1
        '''NALeu,NAL [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property LipidClassProperties() As String
            Get
                Return ResourceManager.GetString("LipidClassProperties", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
