'------------------------------------------------------------------------------
' <auto-generated>
'     此代码由工具生成。
'     运行时版本:4.0.30319.42000
'
'     对此文件的更改可能会导致不正确的行为，并且如果
'     重新生成代码，这些更改将会丢失。
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    '此类是由 StronglyTypedResourceBuilder
    '类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    '若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    '(以 /str 作为命令选项)，或重新生成 VS 项目。
    '''<summary>
    '''  一个强类型的资源类，用于查找本地化的字符串等。
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  返回此类使用的缓存的 ResourceManager 实例。
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("BioNovoGene.Analytical.MassSpectrometry.Lipidomics.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  重写当前线程的 CurrentUICulture 属性，对
        '''  使用此强类型资源类的所有资源查找执行重写。
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  查找类似 Class	Adduct	Ion mode	IsSelected
        '''CAR	[M+H]+	Positive	TRUE
        '''LPC	[M+H]+	Positive	TRUE
        '''LPC	[M+Na]+	Positive	TRUE
        '''LPE	[M+H]+	Positive	TRUE
        '''LPS	[M+H]+	Positive	FALSE
        '''LPG	[M+H]+	Positive	FALSE
        '''LPI	[M+H]+	Positive	FALSE
        '''PC	[M+H]+	Positive	TRUE
        '''PC	[M+Na]+	Positive	TRUE
        '''PE	[M+H]+	Positive	TRUE
        '''PE	[M+Na]+	Positive	TRUE
        '''PI	[M+NH4]+	Positive	TRUE
        '''PI	[M+Na]+	Positive	TRUE
        '''PS	[M+H]+	Positive	TRUE
        '''PS	[M+Na]+	Positive	TRUE
        '''#PT	[M+H]+	Positive	FALSE
        '''PG	[M+NH4]+	Positive	TRUE
        '''BMP	[M+NH4]+	Positive	TRUE
        '''HBMP	[M+NH4]+	Positive	 [字符串的其余部分被截断]&quot;; 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property LbmQueries() As String
            Get
                Return ResourceManager.GetString("LbmQueries", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 LbmClass,DisplayName,AcylChain,AlkylChain,SphingoChain,ExtraAcylChain,TotalChain
        '''Undefined,Undefined,,,,,
        '''Others,Others,,,,,
        '''Unknown,Unknown,,,,,
        '''SPLASH,SPLASH,,,,,
        '''FA,FA,1,,,,1
        '''DMEDFA,DMEDFA,1,,,,1
        '''FAHFA,FAHFA,1,,,1,1
        '''DMEDFAHFA,DMEDFAHFA,1,,,1,1
        '''OxFA,FA,1,,,,1
        '''DMEDOxFA,DMEDFA,1,,,,1
        '''CAR,CAR,1,,,,1
        '''NAE,NAE,1,,,,1
        '''NAGly,NAGly,1,,,1,1
        '''NAGlySer,NAGlySer,1,,,1,1
        '''NAOrn,NAOrn,1,,,1,1
        '''NAPhe,NAPhe,1,,,1,1
        '''NATau,NATau,1,,,1,1
        '''NATryA,NATryA,1,,,1,1
        '''NA5HT,NA5HT,1,,,1,1
        '''NAAla,NAAla,1,,,1,1
        '''NAGln,NAGln,1,,,1,1
        '''NALeu,NAL [字符串的其余部分被截断]&quot;; 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property LipidClassProperties() As String
            Get
                Return ResourceManager.GetString("LipidClassProperties", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
