// *****************************************************************************
// * This is an automatically generated header file for UI Element definition  *
// * resource symbols and values. Please do not modify manually.               *
// *****************************************************************************

#pragma once

#define cmdButtonNew 1001 
#define cmdButtonNew_LabelTitle_RESID 60001
#define cmdButtonNew_LabelDescription_RESID 60002
#define cmdButtonNew_TooltipTitle_RESID 60003
#define cmdButtonNew_TooltipDescription_RESID 60004
#define cmdButtonNew_SmallImages_RESID 60005
#define cmdButtonNew_LargeImages_RESID 60006
#define cmdButtonOpenRaw 1002 
#define cmdButtonOpenRaw_LabelTitle_RESID 60007
#define cmdButtonOpenRaw_LabelDescription_RESID 60008
#define cmdButtonOpenRaw_TooltipTitle_RESID 60009
#define cmdButtonOpenRaw_TooltipDescription_RESID 60010
#define cmdButtonOpenRaw_SmallImages_RESID 60011
#define cmdButtonOpenRaw_LargeImages_RESID 60012
#define cmdButtonSave 1003 
#define cmdButtonSave_LabelTitle_RESID 60013
#define cmdButtonSave_LabelDescription_RESID 60014
#define cmdButtonSave_TooltipTitle_RESID 60015
#define cmdButtonSave_TooltipDescription_RESID 60016
#define cmdButtonSave_SmallImages_RESID 60017
#define cmdButtonSave_LargeImages_RESID 60018
#define cmdButtonExit 1004 
#define cmdButtonExit_LabelTitle_RESID 60019
#define cmdButtonExit_LabelDescription_RESID 60020
#define cmdButtonExit_TooltipTitle_RESID 60021
#define cmdButtonExit_TooltipDescription_RESID 60022
#define cmdButtonExit_SmallImages_RESID 60023
#define cmdButtonExit_LargeImages_RESID 60024
#define cmdMenuGroupFile 1005 
#define cmdMenuGroupFile_LabelTitle_RESID 60025
#define cmdMenuGroupExit 1006 
#define cmdMenuGroupExit_LabelTitle_RESID 60026
#define cmdButtonToolkits 1007 
#define cmdButtonToolkits_LabelTitle_RESID 60027
#define cmdButtonToolkits_LabelDescription_RESID 60028
#define cmdButtonToolkits_TooltipTitle_RESID 60029
#define cmdButtonToolkits_TooltipDescription_RESID 60030
#define cmdButtonToolkits_SmallImages_RESID 60031
#define cmdButtonToolkits_LargeImages_RESID 60032
#define cmdButtonDropA 1008 
#define cmdButtonDropA_LabelTitle_RESID 60033
#define cmdButtonDropA_LabelDescription_RESID 60034
#define cmdButtonDropA_LargeImages_RESID 60035
#define cmdButtonDropB 1009 
#define cmdButtonDropB_LabelTitle_RESID 60036
#define cmdButtonDropB_LabelDescription_RESID 60037
#define cmdButtonDropB_LargeImages_RESID 60038
#define cmdButtonDropC 1010 
#define cmdButtonDropC_LabelTitle_RESID 60039
#define cmdButtonDropC_LabelDescription_RESID 60040
#define cmdButtonDropC_LargeImages_RESID 60041
#define cmdButtonDropD 5010 
#define cmdButtonDropD_LabelTitle_RESID 60042
#define cmdButtonDropD_LabelDescription_RESID 60043
#define cmdButtonDropD_LargeImages_RESID 60044
#define cmdTabMain 1011 
#define cmdTabMain_LabelTitle_RESID 60045
#define cmdTabTools 1012 
#define cmdTabTools_LabelTitle_RESID 60046
#define cmdButtonMzCalculator 1013 
#define cmdButtonMzCalculator_LabelTitle_RESID 60047
#define cmdButtonMzCalculator_SmallImages_RESID 60048
#define cmdButtonMzCalculator_LargeImages_RESID 60049
#define cmdQAT 1015 
#define cmdCustomizeQAT 1018 
#define cmdRecentItems 1014 
#define cmdRecentItems_LabelTitle_RESID 60050
#define cmdHelpButton 1016 
#define cmdButtonImportsRawFiles 1017 
#define cmdButtonImportsRawFiles_LabelTitle_RESID 60051
#define cmdButtonImportsRawFiles_LabelDescription_RESID 60052
#define cmdButtonImportsRawFiles_TooltipTitle_RESID 60053
#define cmdButtonImportsRawFiles_TooltipDescription_RESID 60054
#define cmdButtonImportsRawFiles_SmallImages_RESID 60055
#define cmdButtonImportsRawFiles_LargeImages_RESID 60056
#define cmdButtonResetLayout 1019 
#define cmdButtonResetLayout_LabelTitle_RESID 60057
#define cmdButtonResetLayout_LabelDescription_RESID 60058
#define cmdButtonResetLayout_TooltipTitle_RESID 60059
#define cmdButtonResetLayout_TooltipDescription_RESID 60060
#define cmdButtonResetLayout_SmallImages_RESID 60061
#define cmdButtonResetLayout_LargeImages_RESID 60062
#define cmdTabGroupWindowTools 1023 
#define cmdTabGroupWindowTools_LabelTitle_RESID 60063
#define cmdTabAbout 1020 
#define cmdTabAbout_LabelTitle_RESID 60064
#define cmdButtonAbout 1021 
#define cmdButtonAbout_LabelTitle_RESID 60065
#define cmdButtonAbout_LabelDescription_RESID 60066
#define cmdButtonAbout_TooltipTitle_RESID 60067
#define cmdButtonAbout_LargeImages_RESID 60068
#define cmdButtonBioDeep 1022 
#define cmdButtonBioDeep_LabelTitle_RESID 60069
#define cmdButtonBioDeep_LabelDescription_RESID 60070
#define cmdButtonBioDeep_TooltipTitle_RESID 60071
#define cmdButtonBioDeep_TooltipDescription_RESID 60072
#define cmdButtonBioDeep_LargeImages_RESID 60073
#define cmdTabGroupTableTools 1031 
#define cmdTabGroupTableTools_LabelTitle_RESID 60074
#define cmdTabDesign 1032 
#define cmdTabDesign_LabelTitle_RESID 60075
#define cmdTabLayout 1035 
#define cmdTabLayout_LabelTitle_RESID 60076
#define cmdGroupDesign 1036 
#define cmdGroupDesign_LabelTitle_RESID 60077
#define cmdGroupLayout 1037 
#define cmdGroupLayout_LabelTitle_RESID 60078
#define cmdButtonLayout1 1043 
#define cmdButtonLayout1_LabelTitle_RESID 60079
#define cmdButtonLayout1_LargeImages_RESID 60080
#define cmdButtonLayout2 1044 
#define cmdButtonLayout2_LabelTitle_RESID 60081
#define cmdButtonLayout2_LargeImages_RESID 60082
#define cmdGroupFileActions 1045 
#define cmdGroupFileActions_LabelTitle_RESID 60083
#define cmdGroupToolsActions 1046 
#define cmdGroupToolsActions_LabelTitle_RESID 60084
#define cmdGroupAboutActions 1047 
#define cmdGroupAboutActions_LabelTitle_RESID 60085
#define cmdPPMSpinner 1050 
#define cmdPPMSpinner_LabelTitle_RESID 60086
#define cmdButtonSettings 1051 
#define cmdButtonSettings_LabelTitle_RESID 60087
#define cmdButtonSettings_LabelDescription_RESID 60088
#define cmdButtonSettings_TooltipTitle_RESID 60089
#define cmdButtonSettings_LargeImages_RESID 60090
#define cmdButtonMzSearch 1052 
#define cmdButtonMzSearch_LabelTitle_RESID 60091
#define cmdButtonMzSearch_LabelDescription_RESID 60092
#define cmdButtonMzSearch_TooltipTitle_RESID 60093
#define cmdButtonMzSearch_LargeImages_RESID 60094
#define cmdButtonPageNavBack 1053 
#define cmdButtonPageNavBack_LabelTitle_RESID 60095
#define cmdButtonPageNavBack_LabelDescription_RESID 60096
#define cmdButtonPageNavBack_TooltipTitle_RESID 60097
#define cmdButtonPageNavBack_LargeImages_RESID 60098
#define cmdTabGroupCalculatorTools 1061 
#define cmdTabGroupCalculatorTools_LabelTitle_RESID 60099
#define cmdTabCalculator 1062 
#define cmdTabCalculator_LabelTitle_RESID 60100
#define cmdGroupCalculator 1063 
#define cmdGroupCalculator_LabelTitle_RESID 60101
#define cmdButtonCalculatorExport 1064 
#define cmdButtonCalculatorExport_LabelTitle_RESID 60102
#define cmdButtonCalculatorExport_LabelDescription_RESID 60103
#define cmdButtonCalculatorExport_TooltipTitle_RESID 60104
#define cmdButtonCalculatorExport_TooltipDescription_RESID 60105
#define cmdButtonCalculatorExport_LargeImages_RESID 60106
#define cmdTabGroupExactMassSearchTools 1071 
#define cmdTabGroupExactMassSearchTools_LabelTitle_RESID 60107
#define cmdTabExactMassSearch 1072 
#define cmdTabExactMassSearch_LabelTitle_RESID 60108
#define cmdGroupExactMassSearch 1073 
#define cmdGroupExactMassSearch_LabelTitle_RESID 60109
#define cmdButtonExactMassSearchExport 1074 
#define cmdButtonExactMassSearchExport_LabelTitle_RESID 60110
#define cmdButtonExactMassSearchExport_LargeImages_RESID 60111
#define cmdTabGroupNetworkTools 1081 
#define cmdTabGroupNetworkTools_LabelTitle_RESID 60112
#define cmdTabNetwork 1082 
#define cmdTabNetwork_LabelTitle_RESID 60113
#define cmdGroupNetwork 1083 
#define cmdGroupNetwork_LabelTitle_RESID 60114
#define cmdButtonNetworkExport 1084 
#define cmdButtonNetworkExport_LabelTitle_RESID 60115
#define cmdButtonNetworkExport_LargeImages_RESID 60116
#define cmdButtonNetworkRender 1085 
#define cmdButtonNetworkRender_LabelTitle_RESID 60117
#define cmdButtonNetworkRender_LargeImages_RESID 60118
#define cmdTabGroupFormulaSearchTools 1091 
#define cmdTabGroupFormulaSearchTools_LabelTitle_RESID 60119
#define cmdTabFormulaSearch 1092 
#define cmdTabFormulaSearch_LabelTitle_RESID 60120
#define cmdGroupFormulaSearch 1093 
#define cmdGroupFormulaSearch_LabelTitle_RESID 60121
#define cmdButtonFormulaSearchExport 1094 
#define cmdButtonFormulaSearchExport_LabelTitle_RESID 60122
#define cmdButtonFormulaSearchExport_LabelDescription_RESID 60123
#define cmdButtonFormulaSearchExport_TooltipTitle_RESID 60124
#define cmdButtonFormulaSearchExport_TooltipDescription_RESID 60125
#define cmdButtonFormulaSearchExport_LargeImages_RESID 60126
#define cmdGroupFormulaSearchConfig2 1095 
#define cmdGroupFormulaSearchConfig2_LabelTitle_RESID 60127
#define cmdGroupExit 1096 
#define cmdGroupExit_LabelTitle_RESID 60128
#define cmdComboFormulaSearchProfile3 1099 
#define cmdButtonLicense 1101 
#define cmdButtonLicense_LabelTitle_RESID 60129
#define cmdButtonLicense_LargeImages_RESID 60130
#define cmdButtonExportImage 1104 
#define cmdButtonExportImage_LabelTitle_RESID 60131
#define cmdButtonExportImage_LabelDescription_RESID 60132
#define cmdButtonExportImage_TooltipTitle_RESID 60133
#define cmdButtonExportImage_TooltipDescription_RESID 60134
#define cmdButtonExportImage_SmallImages_RESID 60135
#define cmdButtonExportImage_LargeImages_RESID 60136
#define cmdButtonExportMatrix 1105 
#define cmdButtonExportMatrix_LabelTitle_RESID 60137
#define cmdButtonExportMatrix_LabelDescription_RESID 60138
#define cmdButtonExportMatrix_TooltipTitle_RESID 60139
#define cmdButtonExportMatrix_TooltipDescription_RESID 60140
#define cmdButtonExportMatrix_SmallImages_RESID 60141
#define cmdButtonExportMatrix_LargeImages_RESID 60142
#define cmdContextMap 1106 
#define cmdButtonRsharp 1107 
#define cmdButtonRsharp_LabelTitle_RESID 60143
#define cmdButtonRsharp_LabelDescription_RESID 60144
#define cmdButtonRsharp_TooltipTitle_RESID 60145
#define cmdButtonRsharp_TooltipDescription_RESID 60146
#define cmdButtonRsharp_SmallImages_RESID 60147
#define cmdButtonRsharp_LargeImages_RESID 60148
#define cmdButtonShowStartPage 1108 
#define cmdButtonShowStartPage_LabelTitle_RESID 60149
#define cmdButtonShowStartPage_LabelDescription_RESID 60150
#define cmdButtonShowStartPage_TooltipTitle_RESID 60151
#define cmdButtonShowStartPage_TooltipDescription_RESID 60152
#define cmdButtonShowStartPage_SmallImages_RESID 60153
#define cmdButtonShowStartPage_LargeImages_RESID 60154
#define cmdButtonShowLogWindow 1109 
#define cmdButtonShowLogWindow_LabelTitle_RESID 60155
#define cmdButtonShowLogWindow_LabelDescription_RESID 60156
#define cmdButtonShowLogWindow_TooltipTitle_RESID 60157
#define cmdButtonShowLogWindow_TooltipDescription_RESID 60158
#define cmdButtonShowLogWindow_SmallImages_RESID 60159
#define cmdButtonShowLogWindow_LargeImages_RESID 60160
#define cmdGroupShowViewer 1110 
#define cmdGroupShowViewer_LabelTitle_RESID 60161
#define cmdButtonShowPlotViewer 1111 
#define cmdButtonShowPlotViewer_LabelTitle_RESID 60162
#define cmdButtonShowPlotViewer_LabelDescription_RESID 60163
#define cmdButtonShowPlotViewer_TooltipTitle_RESID 60164
#define cmdButtonShowPlotViewer_LargeImages_RESID 60165
#define cmdButtonShowMatrixViewer 1112 
#define cmdButtonShowMatrixViewer_LabelTitle_RESID 60166
#define cmdButtonShowMatrixViewer_LabelDescription_RESID 60167
#define cmdButtonShowMatrixViewer_TooltipTitle_RESID 60168
#define cmdButtonShowMatrixViewer_LargeImages_RESID 60169
#define cmdGroupShowDockWindows 1120 
#define cmdGroupShowDockWindows_LabelTitle_RESID 60170
#define cmdButtonShowExplorer 1121 
#define cmdButtonShowExplorer_LabelTitle_RESID 60171
#define cmdButtonShowExplorer_LabelDescription_RESID 60172
#define cmdButtonShowExplorer_TooltipTitle_RESID 60173
#define cmdButtonShowExplorer_LargeImages_RESID 60174
#define cmdButtonShowSearchList 1122 
#define cmdButtonShowSearchList_LabelTitle_RESID 60175
#define cmdButtonShowSearchList_LabelDescription_RESID 60176
#define cmdButtonShowSearchList_TooltipTitle_RESID 60177
#define cmdButtonShowSearchList_LargeImages_RESID 60178
#define cmdButtonShowProperties 1123 
#define cmdButtonShowProperties_LabelTitle_RESID 60179
#define cmdButtonShowProperties_LabelDescription_RESID 60180
#define cmdButtonShowProperties_TooltipTitle_RESID 60181
#define cmdButtonShowProperties_LargeImages_RESID 60182
#define cmdTabGroupRscriptTools 1130 
#define cmdTabGroupRscriptTools_LabelTitle_RESID 60183
#define cmdTabRscriptTools 1131 
#define cmdTabRscriptTools_LabelTitle_RESID 60184
#define cmdGroupRscript 1132 
#define cmdGroupRscript_LabelTitle_RESID 60185
#define cmdButtonRunScript 1133 
#define cmdButtonRunScript_LabelTitle_RESID 60186
#define cmdButtonRunScript_LabelDescription_RESID 60187
#define cmdButtonRunScript_TooltipTitle_RESID 60188
#define cmdButtonRunScript_TooltipDescription_RESID 60189
#define cmdButtonRunScript_LargeImages_RESID 60190
#define cmdButtonSaveScript 1134 
#define cmdButtonSaveScript_LabelTitle_RESID 60191
#define cmdButtonSaveScript_LabelDescription_RESID 60192
#define cmdButtonSaveScript_TooltipTitle_RESID 60193
#define cmdButtonSaveScript_TooltipDescription_RESID 60194
#define cmdButtonSaveScript_LargeImages_RESID 60195
#define cmdGroupChromatography 1141 
#define cmdGroupChromatography_LabelTitle_RESID 60196
#define cmdButtonBPC 1143 
#define cmdButtonBPC_LabelTitle_RESID 60197
#define cmdButtonBPC_LabelDescription_RESID 60198
#define cmdButtonBPC_TooltipTitle_RESID 60199
#define cmdButtonBPC_TooltipDescription_RESID 60200
#define cmdButtonBPC_LargeImages_RESID 60201
#define cmdButtonTIC 1144 
#define cmdButtonTIC_LabelTitle_RESID 60202
#define cmdButtonTIC_LabelDescription_RESID 60203
#define cmdButtonTIC_TooltipTitle_RESID 60204
#define cmdButtonTIC_TooltipDescription_RESID 60205
#define cmdButtonTIC_LargeImages_RESID 60206
#define cmdButtonXIC 1145 
#define cmdButtonXIC_LabelTitle_RESID 60207
#define cmdButtonXIC_LabelDescription_RESID 60208
#define cmdButtonXIC_TooltipTitle_RESID 60209
#define cmdButtonXIC_TooltipDescription_RESID 60210
#define cmdButtonXIC_LargeImages_RESID 60211
#define cmdGroupNetworkRenderTool 1150 
#define cmdGroupNetworkRenderTool_LabelTitle_RESID 60212
#define cmdGroupNetworkTools 1151 
#define cmdGroupNetworkTools_LabelTitle_RESID 60213
#define cmdSpinnerSimilarity 1153 
#define cmdSpinnerSimilarity_LabelTitle_RESID 60214
#define cmdSpinnerSimilarity_LabelDescription_RESID 60215
#define cmdSpinnerSimilarity_TooltipTitle_RESID 60216
#define cmdSpinnerSimilarity_TooltipDescription_RESID 60217
#define cmdButtonRefreshNetwork 1154 
#define cmdButtonRefreshNetwork_LabelTitle_RESID 60218
#define cmdButtonRefreshNetwork_LabelDescription_RESID 60219
#define cmdButtonRefreshNetwork_TooltipTitle_RESID 60220
#define cmdButtonRefreshNetwork_TooltipDescription_RESID 60221
#define cmdButtonRefreshNetwork_LargeImages_RESID 60222
#define InternalCmd2_LabelTitle_RESID 60223
#define InternalCmd4_LabelTitle_RESID 60224
