'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports RibbonLib
Imports RibbonLib.Controls
Imports RibbonLib.Interop

Partial Class RibbonItems
    Private _Ribbon As Ribbon, _HelpButton As RibbonHelpButton, _TabMain As RibbonTab, _ButtonNew As RibbonButton, _ButtonOpenRaw As RibbonButton, _ButtonSave As RibbonButton, _ButtonExit As RibbonButton, _TabTools As RibbonTab, _ButtonMzCalculator As RibbonButton, _RecentItems As RibbonRecentItems, _MenuGroupFile As RibbonMenuGroup, _ButtonOpen As RibbonDropDownButton, _ButtonDropA As RibbonButton, _ButtonDropB As RibbonButton, _ButtonDropC As RibbonButton, _MenuGroupExit As RibbonMenuGroup, _QAT As RibbonQuickAccessToolbar

    Private NotInheritable Class Cmd
        Public Const cmdHelpButton As UInteger = 1016
        Public Const cmdTabMain As UInteger = 1011
        Public Const cmdButtonNew As UInteger = 1001
        Public Const cmdButtonOpenRaw As UInteger = 1002
        Public Const cmdButtonSave As UInteger = 1003
        Public Const cmdButtonExit As UInteger = 1004
        Public Const cmdTabTools As UInteger = 1012
        Public Const cmdButtonMzCalculator As UInteger = 1013
        Public Const cmdRecentItems As UInteger = 1014
        Public Const cmdMenuGroupFile As UInteger = 1005
        Public Const cmdButtonOpen As UInteger = 1007
        Public Const cmdButtonDropA As UInteger = 1008
        Public Const cmdButtonDropB As UInteger = 1009
        Public Const cmdButtonDropC As UInteger = 1010
        Public Const cmdMenuGroupExit As UInteger = 1006
        Public Const cmdQAT As UInteger = 1017
        Public Const cmdCustomizeQAT As UInteger = 1018
    End Class

    ' ContextPopup CommandName

    Private Shared initialized As Boolean

    Public Property Ribbon As Ribbon
        Get
            Return _Ribbon
        End Get
        Private Set(ByVal value As Ribbon)
            _Ribbon = value
        End Set
    End Property

    Public Property HelpButton As RibbonHelpButton
        Get
            Return _HelpButton
        End Get
        Private Set(ByVal value As RibbonHelpButton)
            _HelpButton = value
        End Set
    End Property

    Public Property TabMain As RibbonTab
        Get
            Return _TabMain
        End Get
        Private Set(ByVal value As RibbonTab)
            _TabMain = value
        End Set
    End Property

    Public Property ButtonNew As RibbonButton
        Get
            Return _ButtonNew
        End Get
        Private Set(ByVal value As RibbonButton)
            _ButtonNew = value
        End Set
    End Property

    Public Property ButtonOpenRaw As RibbonButton
        Get
            Return _ButtonOpenRaw
        End Get
        Private Set(ByVal value As RibbonButton)
            _ButtonOpenRaw = value
        End Set
    End Property

    Public Property ButtonSave As RibbonButton
        Get
            Return _ButtonSave
        End Get
        Private Set(ByVal value As RibbonButton)
            _ButtonSave = value
        End Set
    End Property

    Public Property ButtonExit As RibbonButton
        Get
            Return _ButtonExit
        End Get
        Private Set(ByVal value As RibbonButton)
            _ButtonExit = value
        End Set
    End Property

    Public Property TabTools As RibbonTab
        Get
            Return _TabTools
        End Get
        Private Set(ByVal value As RibbonTab)
            _TabTools = value
        End Set
    End Property

    Public Property ButtonMzCalculator As RibbonButton
        Get
            Return _ButtonMzCalculator
        End Get
        Private Set(ByVal value As RibbonButton)
            _ButtonMzCalculator = value
        End Set
    End Property

    Public Property RecentItems As RibbonRecentItems
        Get
            Return _RecentItems
        End Get
        Private Set(ByVal value As RibbonRecentItems)
            _RecentItems = value
        End Set
    End Property

    Public Property MenuGroupFile As RibbonMenuGroup
        Get
            Return _MenuGroupFile
        End Get
        Private Set(ByVal value As RibbonMenuGroup)
            _MenuGroupFile = value
        End Set
    End Property

    Public Property ButtonOpen As RibbonDropDownButton
        Get
            Return _ButtonOpen
        End Get
        Private Set(ByVal value As RibbonDropDownButton)
            _ButtonOpen = value
        End Set
    End Property

    Public Property ButtonDropA As RibbonButton
        Get
            Return _ButtonDropA
        End Get
        Private Set(ByVal value As RibbonButton)
            _ButtonDropA = value
        End Set
    End Property

    Public Property ButtonDropB As RibbonButton
        Get
            Return _ButtonDropB
        End Get
        Private Set(ByVal value As RibbonButton)
            _ButtonDropB = value
        End Set
    End Property

    Public Property ButtonDropC As RibbonButton
        Get
            Return _ButtonDropC
        End Get
        Private Set(ByVal value As RibbonButton)
            _ButtonDropC = value
        End Set
    End Property

    Public Property MenuGroupExit As RibbonMenuGroup
        Get
            Return _MenuGroupExit
        End Get
        Private Set(ByVal value As RibbonMenuGroup)
            _MenuGroupExit = value
        End Set
    End Property

    Public Property QAT As RibbonQuickAccessToolbar
        Get
            Return _QAT
        End Get
        Private Set(ByVal value As RibbonQuickAccessToolbar)
            _QAT = value
        End Set
    End Property

    Public Sub New(ByVal ribbon As Ribbon)
        If ribbon Is Nothing Then Throw New ArgumentNullException(NameOf(ribbon), "Parameter is null")
        If initialized Then Return
        Me.Ribbon = ribbon
        HelpButton = New RibbonHelpButton(ribbon, Cmd.cmdHelpButton)
        TabMain = New RibbonTab(ribbon, Cmd.cmdTabMain)
        ButtonNew = New RibbonButton(ribbon, Cmd.cmdButtonNew)
        ButtonOpenRaw = New RibbonButton(ribbon, Cmd.cmdButtonOpenRaw)
        ButtonSave = New RibbonButton(ribbon, Cmd.cmdButtonSave)
        ButtonExit = New RibbonButton(ribbon, Cmd.cmdButtonExit)
        TabTools = New RibbonTab(ribbon, Cmd.cmdTabTools)
        ButtonMzCalculator = New RibbonButton(ribbon, Cmd.cmdButtonMzCalculator)
        RecentItems = New RibbonRecentItems(ribbon, Cmd.cmdRecentItems)
        MenuGroupFile = New RibbonMenuGroup(ribbon, Cmd.cmdMenuGroupFile)
        ButtonOpen = New RibbonDropDownButton(ribbon, Cmd.cmdButtonOpen)
        ButtonDropA = New RibbonButton(ribbon, Cmd.cmdButtonDropA)
        ButtonDropB = New RibbonButton(ribbon, Cmd.cmdButtonDropB)
        ButtonDropC = New RibbonButton(ribbon, Cmd.cmdButtonDropC)
        MenuGroupExit = New RibbonMenuGroup(ribbon, Cmd.cmdMenuGroupExit)
        QAT = New RibbonQuickAccessToolbar(ribbon, Cmd.cmdQAT, Cmd.cmdCustomizeQAT)
        initialized = True
    End Sub
End Class
