'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports RibbonLib
Imports RibbonLib.Controls
Imports RibbonLib.Interop

Partial Class RibbonItems
    Private _Ribbon As Ribbon, _TabGroupTableTools As RibbonTabGroup, _TabDesign As RibbonTab, _GroupDesign As RibbonGroup, _Spinner As RibbonSpinner, _ButtonDesign2 As RibbonButton, _ButtonDesign3 As RibbonButton, _TabLayout As RibbonTab, _GroupLayout As RibbonGroup, _ButtonLayout1 As RibbonButton, _ButtonLayout2 As RibbonButton, _TabGroupCalculatorTools As RibbonTabGroup, _TabCalculator As RibbonTab, _GroupCalculator As RibbonGroup, _ButtonCalculatorExport As RibbonButton, _TabGroupExactMassSearchTools As RibbonTabGroup, _TabExactMassSearch As RibbonTab, _GroupExactMassSearch As RibbonGroup, _ButtonExactMassSearchExport As RibbonButton, _TabGroupNetworkTools As RibbonTabGroup, _TabNetwork As RibbonTab, _GroupNetwork As RibbonGroup, _ButtonNetworkExport As RibbonButton, _ButtonNetworkRender As RibbonButton, _TabGroupFormulaSearchTools As RibbonTabGroup, _TabFormulaSearch As RibbonTab, _GroupFormulaSearch As RibbonGroup, _ButtonFormulaSearchExport As RibbonButton, _GroupFormulaSearchConfig2 As RibbonGroup, _ComboFormulaSearchProfile3 As RibbonComboBox, _HelpButton As RibbonHelpButton, _TabMain As RibbonTab, _GroupFileActions As RibbonGroup, _ButtonNew As RibbonButton, _ButtonOpenRaw As RibbonButton, _ButtonSave As RibbonButton, _ButtonExit As RibbonButton, _TabTools As RibbonTab, _GroupToolsActions As RibbonGroup, _ButtonMzCalculator As RibbonButton, _ButtonMzSearch As RibbonButton, _TabAbout As RibbonTab, _GroupAboutActions As RibbonGroup, _ButtonAbout As RibbonButton, _ButtonSettings As RibbonButton, _RecentItems As RibbonRecentItems, _MenuGroupFile As RibbonMenuGroup, _ButtonOpen As RibbonDropDownButton, _ButtonDropA As RibbonButton, _ButtonDropB As RibbonButton, _ButtonDropC As RibbonButton, _MenuGroupExit As RibbonMenuGroup, _QAT As RibbonQuickAccessToolbar, _ButtonPageNavBack As RibbonButton

    Private NotInheritable Class Cmd
        Public Const cmdTabGroupTableTools As UInteger = 1031
        Public Const cmdTabDesign As UInteger = 1032
        Public Const cmdGroupDesign As UInteger = 1036
        Public Const cmdSpinner As UInteger = 1050
        Public Const cmdButtonDesign2 As UInteger = 1041
        Public Const cmdButtonDesign3 As UInteger = 1042
        Public Const cmdTabLayout As UInteger = 1035
        Public Const cmdGroupLayout As UInteger = 1037
        Public Const cmdButtonLayout1 As UInteger = 1043
        Public Const cmdButtonLayout2 As UInteger = 1044
        Public Const cmdTabGroupCalculatorTools As UInteger = 1061
        Public Const cmdTabCalculator As UInteger = 1062
        Public Const cmdGroupCalculator As UInteger = 1063
        Public Const cmdButtonCalculatorExport As UInteger = 1064
        Public Const cmdTabGroupExactMassSearchTools As UInteger = 1071
        Public Const cmdTabExactMassSearch As UInteger = 1072
        Public Const cmdGroupExactMassSearch As UInteger = 1073
        Public Const cmdButtonExactMassSearchExport As UInteger = 1074
        Public Const cmdTabGroupNetworkTools As UInteger = 1081
        Public Const cmdTabNetwork As UInteger = 1082
        Public Const cmdGroupNetwork As UInteger = 1083
        Public Const cmdButtonNetworkExport As UInteger = 1084
        Public Const cmdButtonNetworkRender As UInteger = 1085
        Public Const cmdTabGroupFormulaSearchTools As UInteger = 1091
        Public Const cmdTabFormulaSearch As UInteger = 1092
        Public Const cmdGroupFormulaSearch As UInteger = 1093
        Public Const cmdButtonFormulaSearchExport As UInteger = 1094
        Public Const cmdGroupFormulaSearchConfig2 As UInteger = 1095
        Public Const cmdComboFormulaSearchProfile3 As UInteger = 1099
        Public Const cmdHelpButton As UInteger = 1016
        Public Const cmdTabMain As UInteger = 1011
        Public Const cmdGroupFileActions As UInteger = 1045
        Public Const cmdButtonNew As UInteger = 1001
        Public Const cmdButtonOpenRaw As UInteger = 1002
        Public Const cmdButtonSave As UInteger = 1003
        Public Const cmdButtonExit As UInteger = 1004
        Public Const cmdTabTools As UInteger = 1012
        Public Const cmdGroupToolsActions As UInteger = 1046
        Public Const cmdButtonMzCalculator As UInteger = 1013
        Public Const cmdButtonMzSearch As UInteger = 1052
        Public Const cmdTabAbout As UInteger = 1020
        Public Const cmdGroupAboutActions As UInteger = 1047
        Public Const cmdButtonAbout As UInteger = 1021
        Public Const cmdButtonSettings As UInteger = 1051
        Public Const cmdRecentItems As UInteger = 1014
        Public Const cmdMenuGroupFile As UInteger = 1005
        Public Const cmdButtonOpen As UInteger = 1007
        Public Const cmdButtonDropA As UInteger = 1008
        Public Const cmdButtonDropB As UInteger = 1009
        Public Const cmdButtonDropC As UInteger = 1010
        Public Const cmdMenuGroupExit As UInteger = 1006
        Public Const cmdQAT As UInteger = 1015
        Public Const cmdButtonPageNavBack As UInteger = 1053
        Public Const cmdCustomizeQAT As UInteger = 1018
    End Class

    ' ContextPopup CommandName

    Private Shared initialized As Boolean

    Public Property Ribbon As Ribbon
        Get
            Return _Ribbon
        End Get
        Private Set(ByVal value As Ribbon)
            _Ribbon = value
        End Set
    End Property

    Public Property TabGroupTableTools As RibbonTabGroup
        Get
            Return _TabGroupTableTools
        End Get
        Private Set(ByVal value As RibbonTabGroup)
            _TabGroupTableTools = value
        End Set
    End Property

    Public Property TabDesign As RibbonTab
        Get
            Return _TabDesign
        End Get
        Private Set(ByVal value As RibbonTab)
            _TabDesign = value
        End Set
    End Property

    Public Property GroupDesign As RibbonGroup
        Get
            Return _GroupDesign
        End Get
        Private Set(ByVal value As RibbonGroup)
            _GroupDesign = value
        End Set
    End Property

    Public Property Spinner As RibbonSpinner
        Get
            Return _Spinner
        End Get
        Private Set(ByVal value As RibbonSpinner)
            _Spinner = value
        End Set
    End Property

    Public Property ButtonDesign2 As RibbonButton
        Get
            Return _ButtonDesign2
        End Get
        Private Set(ByVal value As RibbonButton)
            _ButtonDesign2 = value
        End Set
    End Property

    Public Property ButtonDesign3 As RibbonButton
        Get
            Return _ButtonDesign3
        End Get
        Private Set(ByVal value As RibbonButton)
            _ButtonDesign3 = value
        End Set
    End Property

    Public Property TabLayout As RibbonTab
        Get
            Return _TabLayout
        End Get
        Private Set(ByVal value As RibbonTab)
            _TabLayout = value
        End Set
    End Property

    Public Property GroupLayout As RibbonGroup
        Get
            Return _GroupLayout
        End Get
        Private Set(ByVal value As RibbonGroup)
            _GroupLayout = value
        End Set
    End Property

    Public Property ButtonLayout1 As RibbonButton
        Get
            Return _ButtonLayout1
        End Get
        Private Set(ByVal value As RibbonButton)
            _ButtonLayout1 = value
        End Set
    End Property

    Public Property ButtonLayout2 As RibbonButton
        Get
            Return _ButtonLayout2
        End Get
        Private Set(ByVal value As RibbonButton)
            _ButtonLayout2 = value
        End Set
    End Property

    Public Property TabGroupCalculatorTools As RibbonTabGroup
        Get
            Return _TabGroupCalculatorTools
        End Get
        Private Set(ByVal value As RibbonTabGroup)
            _TabGroupCalculatorTools = value
        End Set
    End Property

    Public Property TabCalculator As RibbonTab
        Get
            Return _TabCalculator
        End Get
        Private Set(ByVal value As RibbonTab)
            _TabCalculator = value
        End Set
    End Property

    Public Property GroupCalculator As RibbonGroup
        Get
            Return _GroupCalculator
        End Get
        Private Set(ByVal value As RibbonGroup)
            _GroupCalculator = value
        End Set
    End Property

    Public Property ButtonCalculatorExport As RibbonButton
        Get
            Return _ButtonCalculatorExport
        End Get
        Private Set(ByVal value As RibbonButton)
            _ButtonCalculatorExport = value
        End Set
    End Property

    Public Property TabGroupExactMassSearchTools As RibbonTabGroup
        Get
            Return _TabGroupExactMassSearchTools
        End Get
        Private Set(ByVal value As RibbonTabGroup)
            _TabGroupExactMassSearchTools = value
        End Set
    End Property

    Public Property TabExactMassSearch As RibbonTab
        Get
            Return _TabExactMassSearch
        End Get
        Private Set(ByVal value As RibbonTab)
            _TabExactMassSearch = value
        End Set
    End Property

    Public Property GroupExactMassSearch As RibbonGroup
        Get
            Return _GroupExactMassSearch
        End Get
        Private Set(ByVal value As RibbonGroup)
            _GroupExactMassSearch = value
        End Set
    End Property

    Public Property ButtonExactMassSearchExport As RibbonButton
        Get
            Return _ButtonExactMassSearchExport
        End Get
        Private Set(ByVal value As RibbonButton)
            _ButtonExactMassSearchExport = value
        End Set
    End Property

    Public Property TabGroupNetworkTools As RibbonTabGroup
        Get
            Return _TabGroupNetworkTools
        End Get
        Private Set(ByVal value As RibbonTabGroup)
            _TabGroupNetworkTools = value
        End Set
    End Property

    Public Property TabNetwork As RibbonTab
        Get
            Return _TabNetwork
        End Get
        Private Set(ByVal value As RibbonTab)
            _TabNetwork = value
        End Set
    End Property

    Public Property GroupNetwork As RibbonGroup
        Get
            Return _GroupNetwork
        End Get
        Private Set(ByVal value As RibbonGroup)
            _GroupNetwork = value
        End Set
    End Property

    Public Property ButtonNetworkExport As RibbonButton
        Get
            Return _ButtonNetworkExport
        End Get
        Private Set(ByVal value As RibbonButton)
            _ButtonNetworkExport = value
        End Set
    End Property

    Public Property ButtonNetworkRender As RibbonButton
        Get
            Return _ButtonNetworkRender
        End Get
        Private Set(ByVal value As RibbonButton)
            _ButtonNetworkRender = value
        End Set
    End Property

    Public Property TabGroupFormulaSearchTools As RibbonTabGroup
        Get
            Return _TabGroupFormulaSearchTools
        End Get
        Private Set(ByVal value As RibbonTabGroup)
            _TabGroupFormulaSearchTools = value
        End Set
    End Property

    Public Property TabFormulaSearch As RibbonTab
        Get
            Return _TabFormulaSearch
        End Get
        Private Set(ByVal value As RibbonTab)
            _TabFormulaSearch = value
        End Set
    End Property

    Public Property GroupFormulaSearch As RibbonGroup
        Get
            Return _GroupFormulaSearch
        End Get
        Private Set(ByVal value As RibbonGroup)
            _GroupFormulaSearch = value
        End Set
    End Property

    Public Property ButtonFormulaSearchExport As RibbonButton
        Get
            Return _ButtonFormulaSearchExport
        End Get
        Private Set(ByVal value As RibbonButton)
            _ButtonFormulaSearchExport = value
        End Set
    End Property

    Public Property GroupFormulaSearchConfig2 As RibbonGroup
        Get
            Return _GroupFormulaSearchConfig2
        End Get
        Private Set(ByVal value As RibbonGroup)
            _GroupFormulaSearchConfig2 = value
        End Set
    End Property

    Public Property ComboFormulaSearchProfile3 As RibbonComboBox
        Get
            Return _ComboFormulaSearchProfile3
        End Get
        Private Set(ByVal value As RibbonComboBox)
            _ComboFormulaSearchProfile3 = value
        End Set
    End Property

    Public Property HelpButton As RibbonHelpButton
        Get
            Return _HelpButton
        End Get
        Private Set(ByVal value As RibbonHelpButton)
            _HelpButton = value
        End Set
    End Property

    Public Property TabMain As RibbonTab
        Get
            Return _TabMain
        End Get
        Private Set(ByVal value As RibbonTab)
            _TabMain = value
        End Set
    End Property

    Public Property GroupFileActions As RibbonGroup
        Get
            Return _GroupFileActions
        End Get
        Private Set(ByVal value As RibbonGroup)
            _GroupFileActions = value
        End Set
    End Property

    Public Property ButtonNew As RibbonButton
        Get
            Return _ButtonNew
        End Get
        Private Set(ByVal value As RibbonButton)
            _ButtonNew = value
        End Set
    End Property

    Public Property ButtonOpenRaw As RibbonButton
        Get
            Return _ButtonOpenRaw
        End Get
        Private Set(ByVal value As RibbonButton)
            _ButtonOpenRaw = value
        End Set
    End Property

    Public Property ButtonSave As RibbonButton
        Get
            Return _ButtonSave
        End Get
        Private Set(ByVal value As RibbonButton)
            _ButtonSave = value
        End Set
    End Property

    Public Property ButtonExit As RibbonButton
        Get
            Return _ButtonExit
        End Get
        Private Set(ByVal value As RibbonButton)
            _ButtonExit = value
        End Set
    End Property

    Public Property TabTools As RibbonTab
        Get
            Return _TabTools
        End Get
        Private Set(ByVal value As RibbonTab)
            _TabTools = value
        End Set
    End Property

    Public Property GroupToolsActions As RibbonGroup
        Get
            Return _GroupToolsActions
        End Get
        Private Set(ByVal value As RibbonGroup)
            _GroupToolsActions = value
        End Set
    End Property

    Public Property ButtonMzCalculator As RibbonButton
        Get
            Return _ButtonMzCalculator
        End Get
        Private Set(ByVal value As RibbonButton)
            _ButtonMzCalculator = value
        End Set
    End Property

    Public Property ButtonMzSearch As RibbonButton
        Get
            Return _ButtonMzSearch
        End Get
        Private Set(ByVal value As RibbonButton)
            _ButtonMzSearch = value
        End Set
    End Property

    Public Property TabAbout As RibbonTab
        Get
            Return _TabAbout
        End Get
        Private Set(ByVal value As RibbonTab)
            _TabAbout = value
        End Set
    End Property

    Public Property GroupAboutActions As RibbonGroup
        Get
            Return _GroupAboutActions
        End Get
        Private Set(ByVal value As RibbonGroup)
            _GroupAboutActions = value
        End Set
    End Property

    Public Property ButtonAbout As RibbonButton
        Get
            Return _ButtonAbout
        End Get
        Private Set(ByVal value As RibbonButton)
            _ButtonAbout = value
        End Set
    End Property

    Public Property ButtonSettings As RibbonButton
        Get
            Return _ButtonSettings
        End Get
        Private Set(ByVal value As RibbonButton)
            _ButtonSettings = value
        End Set
    End Property

    Public Property RecentItems As RibbonRecentItems
        Get
            Return _RecentItems
        End Get
        Private Set(ByVal value As RibbonRecentItems)
            _RecentItems = value
        End Set
    End Property

    Public Property MenuGroupFile As RibbonMenuGroup
        Get
            Return _MenuGroupFile
        End Get
        Private Set(ByVal value As RibbonMenuGroup)
            _MenuGroupFile = value
        End Set
    End Property

    Public Property ButtonOpen As RibbonDropDownButton
        Get
            Return _ButtonOpen
        End Get
        Private Set(ByVal value As RibbonDropDownButton)
            _ButtonOpen = value
        End Set
    End Property

    Public Property ButtonDropA As RibbonButton
        Get
            Return _ButtonDropA
        End Get
        Private Set(ByVal value As RibbonButton)
            _ButtonDropA = value
        End Set
    End Property

    Public Property ButtonDropB As RibbonButton
        Get
            Return _ButtonDropB
        End Get
        Private Set(ByVal value As RibbonButton)
            _ButtonDropB = value
        End Set
    End Property

    Public Property ButtonDropC As RibbonButton
        Get
            Return _ButtonDropC
        End Get
        Private Set(ByVal value As RibbonButton)
            _ButtonDropC = value
        End Set
    End Property

    Public Property MenuGroupExit As RibbonMenuGroup
        Get
            Return _MenuGroupExit
        End Get
        Private Set(ByVal value As RibbonMenuGroup)
            _MenuGroupExit = value
        End Set
    End Property

    Public Property QAT As RibbonQuickAccessToolbar
        Get
            Return _QAT
        End Get
        Private Set(ByVal value As RibbonQuickAccessToolbar)
            _QAT = value
        End Set
    End Property

    Public Property ButtonPageNavBack As RibbonButton
        Get
            Return _ButtonPageNavBack
        End Get
        Private Set(ByVal value As RibbonButton)
            _ButtonPageNavBack = value
        End Set
    End Property

    Public Sub New(ByVal ribbon As Ribbon)
        If ribbon Is Nothing Then Throw New ArgumentNullException(NameOf(ribbon), "Parameter is null")
        If initialized Then Return
        Me.Ribbon = ribbon
        TabGroupTableTools = New RibbonTabGroup(ribbon, Cmd.cmdTabGroupTableTools)
        TabDesign = New RibbonTab(ribbon, Cmd.cmdTabDesign)
        GroupDesign = New RibbonGroup(ribbon, Cmd.cmdGroupDesign)
        Spinner = New RibbonSpinner(ribbon, Cmd.cmdSpinner)
        ButtonDesign2 = New RibbonButton(ribbon, Cmd.cmdButtonDesign2)
        ButtonDesign3 = New RibbonButton(ribbon, Cmd.cmdButtonDesign3)
        TabLayout = New RibbonTab(ribbon, Cmd.cmdTabLayout)
        GroupLayout = New RibbonGroup(ribbon, Cmd.cmdGroupLayout)
        ButtonLayout1 = New RibbonButton(ribbon, Cmd.cmdButtonLayout1)
        ButtonLayout2 = New RibbonButton(ribbon, Cmd.cmdButtonLayout2)
        TabGroupCalculatorTools = New RibbonTabGroup(ribbon, Cmd.cmdTabGroupCalculatorTools)
        TabCalculator = New RibbonTab(ribbon, Cmd.cmdTabCalculator)
        GroupCalculator = New RibbonGroup(ribbon, Cmd.cmdGroupCalculator)
        ButtonCalculatorExport = New RibbonButton(ribbon, Cmd.cmdButtonCalculatorExport)
        TabGroupExactMassSearchTools = New RibbonTabGroup(ribbon, Cmd.cmdTabGroupExactMassSearchTools)
        TabExactMassSearch = New RibbonTab(ribbon, Cmd.cmdTabExactMassSearch)
        GroupExactMassSearch = New RibbonGroup(ribbon, Cmd.cmdGroupExactMassSearch)
        ButtonExactMassSearchExport = New RibbonButton(ribbon, Cmd.cmdButtonExactMassSearchExport)
        TabGroupNetworkTools = New RibbonTabGroup(ribbon, Cmd.cmdTabGroupNetworkTools)
        TabNetwork = New RibbonTab(ribbon, Cmd.cmdTabNetwork)
        GroupNetwork = New RibbonGroup(ribbon, Cmd.cmdGroupNetwork)
        ButtonNetworkExport = New RibbonButton(ribbon, Cmd.cmdButtonNetworkExport)
        ButtonNetworkRender = New RibbonButton(ribbon, Cmd.cmdButtonNetworkRender)
        TabGroupFormulaSearchTools = New RibbonTabGroup(ribbon, Cmd.cmdTabGroupFormulaSearchTools)
        TabFormulaSearch = New RibbonTab(ribbon, Cmd.cmdTabFormulaSearch)
        GroupFormulaSearch = New RibbonGroup(ribbon, Cmd.cmdGroupFormulaSearch)
        ButtonFormulaSearchExport = New RibbonButton(ribbon, Cmd.cmdButtonFormulaSearchExport)
        GroupFormulaSearchConfig2 = New RibbonGroup(ribbon, Cmd.cmdGroupFormulaSearchConfig2)
        ComboFormulaSearchProfile3 = New RibbonComboBox(ribbon, Cmd.cmdComboFormulaSearchProfile3)
        HelpButton = New RibbonHelpButton(ribbon, Cmd.cmdHelpButton)
        TabMain = New RibbonTab(ribbon, Cmd.cmdTabMain)
        GroupFileActions = New RibbonGroup(ribbon, Cmd.cmdGroupFileActions)
        ButtonNew = New RibbonButton(ribbon, Cmd.cmdButtonNew)
        ButtonOpenRaw = New RibbonButton(ribbon, Cmd.cmdButtonOpenRaw)
        ButtonSave = New RibbonButton(ribbon, Cmd.cmdButtonSave)
        ButtonExit = New RibbonButton(ribbon, Cmd.cmdButtonExit)
        TabTools = New RibbonTab(ribbon, Cmd.cmdTabTools)
        GroupToolsActions = New RibbonGroup(ribbon, Cmd.cmdGroupToolsActions)
        ButtonMzCalculator = New RibbonButton(ribbon, Cmd.cmdButtonMzCalculator)
        ButtonMzSearch = New RibbonButton(ribbon, Cmd.cmdButtonMzSearch)
        TabAbout = New RibbonTab(ribbon, Cmd.cmdTabAbout)
        GroupAboutActions = New RibbonGroup(ribbon, Cmd.cmdGroupAboutActions)
        ButtonAbout = New RibbonButton(ribbon, Cmd.cmdButtonAbout)
        ButtonSettings = New RibbonButton(ribbon, Cmd.cmdButtonSettings)
        RecentItems = New RibbonRecentItems(ribbon, Cmd.cmdRecentItems)
        MenuGroupFile = New RibbonMenuGroup(ribbon, Cmd.cmdMenuGroupFile)
        ButtonOpen = New RibbonDropDownButton(ribbon, Cmd.cmdButtonOpen)
        ButtonDropA = New RibbonButton(ribbon, Cmd.cmdButtonDropA)
        ButtonDropB = New RibbonButton(ribbon, Cmd.cmdButtonDropB)
        ButtonDropC = New RibbonButton(ribbon, Cmd.cmdButtonDropC)
        MenuGroupExit = New RibbonMenuGroup(ribbon, Cmd.cmdMenuGroupExit)
        QAT = New RibbonQuickAccessToolbar(ribbon, Cmd.cmdQAT, Cmd.cmdCustomizeQAT)
        ButtonPageNavBack = New RibbonButton(ribbon, Cmd.cmdButtonPageNavBack)
        initialized = True
    End Sub
End Class
