// *****************************************************************************
// * This is an automatically generated header file for UI Element definition  *
// * resource symbols and values. Please do not modify manually.               *
// *****************************************************************************

#pragma once

#define cmdButtonAbout 1021 
#define cmdButtonAbout_LabelTitle_RESID 66
#define cmdButtonAbout_LabelDescription_RESID 67
#define cmdButtonAbout_TooltipTitle_RESID 68
#define cmdButtonAbout_LargeImages_RESID 69
#define cmdButtonBioDeep 1022 
#define cmdButtonBioDeep_LabelTitle_RESID 70
#define cmdButtonBioDeep_LabelDescription_RESID 71
#define cmdButtonBioDeep_TooltipTitle_RESID 72
#define cmdButtonBioDeep_TooltipDescription_RESID 73
#define cmdButtonBioDeep_LargeImages_RESID 74
#define cmdButtonBPC 1143 
#define cmdButtonBPC_LabelTitle_RESID 203
#define cmdButtonBPC_LabelDescription_RESID 204
#define cmdButtonBPC_TooltipTitle_RESID 205
#define cmdButtonBPC_TooltipDescription_RESID 206
#define cmdButtonBPC_LargeImages_RESID 207
#define cmdButtonCalculatorExport 1064 
#define cmdButtonCalculatorExport_LabelTitle_RESID 104
#define cmdButtonCalculatorExport_LabelDescription_RESID 105
#define cmdButtonCalculatorExport_TooltipTitle_RESID 106
#define cmdButtonCalculatorExport_TooltipDescription_RESID 107
#define cmdButtonCalculatorExport_LargeImages_RESID 108
#define cmdButtonDropA 1008 
#define cmdButtonDropA_LabelTitle_RESID 34
#define cmdButtonDropA_LabelDescription_RESID 35
#define cmdButtonDropA_LargeImages_RESID 36
#define cmdButtonDropB 1009 
#define cmdButtonDropB_LabelTitle_RESID 37
#define cmdButtonDropB_LabelDescription_RESID 38
#define cmdButtonDropB_LargeImages_RESID 39
#define cmdButtonDropC 1010 
#define cmdButtonDropC_LabelTitle_RESID 40
#define cmdButtonDropC_LabelDescription_RESID 41
#define cmdButtonDropC_LargeImages_RESID 42
#define cmdButtonDropD 5010 
#define cmdButtonDropD_LabelTitle_RESID 43
#define cmdButtonDropD_LabelDescription_RESID 44
#define cmdButtonDropD_LargeImages_RESID 45
#define cmdButtonExactMassSearchExport 1074 
#define cmdButtonExactMassSearchExport_LabelTitle_RESID 112
#define cmdButtonExactMassSearchExport_LargeImages_RESID 113
#define cmdButtonExit 1004 
#define cmdButtonExit_LabelTitle_RESID 20
#define cmdButtonExit_LabelDescription_RESID 21
#define cmdButtonExit_TooltipTitle_RESID 22
#define cmdButtonExit_TooltipDescription_RESID 23
#define cmdButtonExit_SmallImages_RESID 24
#define cmdButtonExit_LargeImages_RESID 25
#define cmdButtonExportImage 1104 
#define cmdButtonExportImage_LabelTitle_RESID 137
#define cmdButtonExportImage_LabelDescription_RESID 138
#define cmdButtonExportImage_TooltipTitle_RESID 139
#define cmdButtonExportImage_TooltipDescription_RESID 140
#define cmdButtonExportImage_SmallImages_RESID 141
#define cmdButtonExportImage_LargeImages_RESID 142
#define cmdButtonExportMatrix 1105 
#define cmdButtonExportMatrix_LabelTitle_RESID 143
#define cmdButtonExportMatrix_LabelDescription_RESID 144
#define cmdButtonExportMatrix_TooltipTitle_RESID 145
#define cmdButtonExportMatrix_TooltipDescription_RESID 146
#define cmdButtonExportMatrix_SmallImages_RESID 147
#define cmdButtonExportMatrix_LargeImages_RESID 148
#define cmdButtonFormulaSearchExport 1094 
#define cmdButtonFormulaSearchExport_LabelTitle_RESID 124
#define cmdButtonFormulaSearchExport_LabelDescription_RESID 125
#define cmdButtonFormulaSearchExport_TooltipTitle_RESID 126
#define cmdButtonFormulaSearchExport_TooltipDescription_RESID 127
#define cmdButtonFormulaSearchExport_LargeImages_RESID 128
#define cmdButtonImportsRawFiles 1017 
#define cmdButtonImportsRawFiles_LabelTitle_RESID 52
#define cmdButtonImportsRawFiles_LabelDescription_RESID 53
#define cmdButtonImportsRawFiles_TooltipTitle_RESID 54
#define cmdButtonImportsRawFiles_TooltipDescription_RESID 55
#define cmdButtonImportsRawFiles_SmallImages_RESID 56
#define cmdButtonImportsRawFiles_LargeImages_RESID 57
#define cmdButtonLayout1 1043 
#define cmdButtonLayout1_LabelTitle_RESID 80
#define cmdButtonLayout1_LargeImages_RESID 81
#define cmdButtonLayout2 1044 
#define cmdButtonLayout2_LabelTitle_RESID 82
#define cmdButtonLayout2_LargeImages_RESID 83
#define cmdButtonLicense 1101 
#define cmdButtonLicense_LabelTitle_RESID 131
#define cmdButtonLicense_LargeImages_RESID 132
#define cmdButtonMsDemo 1168 
#define cmdButtonMsDemo_LabelTitle_RESID 235
#define cmdButtonMsDemo_LabelDescription_RESID 236
#define cmdButtonMsDemo_TooltipTitle_RESID 237
#define cmdButtonMsDemo_TooltipDescription_RESID 238
#define cmdButtonMsDemo_LargeImages_RESID 239
#define cmdButtonMsImaging 1167 
#define cmdButtonMsImaging_LabelTitle_RESID 230
#define cmdButtonMsImaging_LabelDescription_RESID 231
#define cmdButtonMsImaging_TooltipTitle_RESID 232
#define cmdButtonMsImaging_TooltipDescription_RESID 233
#define cmdButtonMsImaging_LargeImages_RESID 234
#define cmdButtonMzCalculator 1013 
#define cmdButtonMzCalculator_LabelTitle_RESID 48
#define cmdButtonMzCalculator_SmallImages_RESID 49
#define cmdButtonMzCalculator_LargeImages_RESID 50
#define cmdButtonMzSearch 1052 
#define cmdButtonMzSearch_LabelTitle_RESID 93
#define cmdButtonMzSearch_LabelDescription_RESID 94
#define cmdButtonMzSearch_TooltipTitle_RESID 95
#define cmdButtonMzSearch_LargeImages_RESID 96
#define cmdButtonNetworkExport 1084 
#define cmdButtonNetworkExport_LabelTitle_RESID 117
#define cmdButtonNetworkExport_LargeImages_RESID 118
#define cmdButtonNetworkRender 1085 
#define cmdButtonNetworkRender_LabelTitle_RESID 119
#define cmdButtonNetworkRender_LargeImages_RESID 120
#define cmdButtonNew 1001 
#define cmdButtonNew_LabelTitle_RESID 2
#define cmdButtonNew_LabelDescription_RESID 3
#define cmdButtonNew_TooltipTitle_RESID 4
#define cmdButtonNew_TooltipDescription_RESID 5
#define cmdButtonNew_SmallImages_RESID 6
#define cmdButtonNew_LargeImages_RESID 7
#define cmdButtonOpenRaw 1002 
#define cmdButtonOpenRaw_LabelTitle_RESID 8
#define cmdButtonOpenRaw_LabelDescription_RESID 9
#define cmdButtonOpenRaw_TooltipTitle_RESID 10
#define cmdButtonOpenRaw_TooltipDescription_RESID 11
#define cmdButtonOpenRaw_SmallImages_RESID 12
#define cmdButtonOpenRaw_LargeImages_RESID 13
#define cmdButtonPageNavBack 1053 
#define cmdButtonPageNavBack_LabelTitle_RESID 97
#define cmdButtonPageNavBack_LabelDescription_RESID 98
#define cmdButtonPageNavBack_TooltipTitle_RESID 99
#define cmdButtonPageNavBack_LargeImages_RESID 100
#define cmdButtonRefreshNetwork 1154 
#define cmdButtonRefreshNetwork_LabelTitle_RESID 224
#define cmdButtonRefreshNetwork_LabelDescription_RESID 225
#define cmdButtonRefreshNetwork_TooltipTitle_RESID 226
#define cmdButtonRefreshNetwork_TooltipDescription_RESID 227
#define cmdButtonRefreshNetwork_LargeImages_RESID 228
#define cmdButtonResetLayout 1019 
#define cmdButtonResetLayout_LabelTitle_RESID 58
#define cmdButtonResetLayout_LabelDescription_RESID 59
#define cmdButtonResetLayout_TooltipTitle_RESID 60
#define cmdButtonResetLayout_TooltipDescription_RESID 61
#define cmdButtonResetLayout_SmallImages_RESID 62
#define cmdButtonResetLayout_LargeImages_RESID 63
#define cmdButtonRsharp 1107 
#define cmdButtonRsharp_LabelTitle_RESID 149
#define cmdButtonRsharp_LabelDescription_RESID 150
#define cmdButtonRsharp_TooltipTitle_RESID 151
#define cmdButtonRsharp_TooltipDescription_RESID 152
#define cmdButtonRsharp_SmallImages_RESID 153
#define cmdButtonRsharp_LargeImages_RESID 154
#define cmdButtonRunScript 1133 
#define cmdButtonRunScript_LabelTitle_RESID 192
#define cmdButtonRunScript_LabelDescription_RESID 193
#define cmdButtonRunScript_TooltipTitle_RESID 194
#define cmdButtonRunScript_TooltipDescription_RESID 195
#define cmdButtonRunScript_LargeImages_RESID 196
#define cmdButtonSave 1003 
#define cmdButtonSave_LabelTitle_RESID 14
#define cmdButtonSave_LabelDescription_RESID 15
#define cmdButtonSave_TooltipTitle_RESID 16
#define cmdButtonSave_TooltipDescription_RESID 17
#define cmdButtonSave_SmallImages_RESID 18
#define cmdButtonSave_LargeImages_RESID 19
#define cmdButtonSaveScript 1134 
#define cmdButtonSaveScript_LabelTitle_RESID 197
#define cmdButtonSaveScript_LabelDescription_RESID 198
#define cmdButtonSaveScript_TooltipTitle_RESID 199
#define cmdButtonSaveScript_TooltipDescription_RESID 200
#define cmdButtonSaveScript_LargeImages_RESID 201
#define cmdButtonSettings 1051 
#define cmdButtonSettings_LabelTitle_RESID 89
#define cmdButtonSettings_LabelDescription_RESID 90
#define cmdButtonSettings_TooltipTitle_RESID 91
#define cmdButtonSettings_LargeImages_RESID 92
#define cmdButtonShowExplorer 1121 
#define cmdButtonShowExplorer_LabelTitle_RESID 177
#define cmdButtonShowExplorer_LabelDescription_RESID 178
#define cmdButtonShowExplorer_TooltipTitle_RESID 179
#define cmdButtonShowExplorer_LargeImages_RESID 180
#define cmdButtonShowLogWindow 1109 
#define cmdButtonShowLogWindow_LabelTitle_RESID 161
#define cmdButtonShowLogWindow_LabelDescription_RESID 162
#define cmdButtonShowLogWindow_TooltipTitle_RESID 163
#define cmdButtonShowLogWindow_TooltipDescription_RESID 164
#define cmdButtonShowLogWindow_SmallImages_RESID 165
#define cmdButtonShowLogWindow_LargeImages_RESID 166
#define cmdButtonShowMatrixViewer 1112 
#define cmdButtonShowMatrixViewer_LabelTitle_RESID 172
#define cmdButtonShowMatrixViewer_LabelDescription_RESID 173
#define cmdButtonShowMatrixViewer_TooltipTitle_RESID 174
#define cmdButtonShowMatrixViewer_LargeImages_RESID 175
#define cmdButtonShowPlotViewer 1111 
#define cmdButtonShowPlotViewer_LabelTitle_RESID 168
#define cmdButtonShowPlotViewer_LabelDescription_RESID 169
#define cmdButtonShowPlotViewer_TooltipTitle_RESID 170
#define cmdButtonShowPlotViewer_LargeImages_RESID 171
#define cmdButtonShowProperties 1123 
#define cmdButtonShowProperties_LabelTitle_RESID 185
#define cmdButtonShowProperties_LabelDescription_RESID 186
#define cmdButtonShowProperties_TooltipTitle_RESID 187
#define cmdButtonShowProperties_LargeImages_RESID 188
#define cmdButtonShowSearchList 1122 
#define cmdButtonShowSearchList_LabelTitle_RESID 181
#define cmdButtonShowSearchList_LabelDescription_RESID 182
#define cmdButtonShowSearchList_TooltipTitle_RESID 183
#define cmdButtonShowSearchList_LargeImages_RESID 184
#define cmdButtonShowSpectrumSearchPage 1102 
#define cmdButtonShowSpectrumSearchPage_LabelTitle_RESID 133
#define cmdButtonShowSpectrumSearchPage_LabelDescription_RESID 134
#define cmdButtonShowSpectrumSearchPage_SmallImages_RESID 135
#define cmdButtonShowSpectrumSearchPage_LargeImages_RESID 136
#define cmdButtonShowStartPage 1108 
#define cmdButtonShowStartPage_LabelTitle_RESID 155
#define cmdButtonShowStartPage_LabelDescription_RESID 156
#define cmdButtonShowStartPage_TooltipTitle_RESID 157
#define cmdButtonShowStartPage_TooltipDescription_RESID 158
#define cmdButtonShowStartPage_SmallImages_RESID 159
#define cmdButtonShowStartPage_LargeImages_RESID 160
#define cmdButtonTIC 1144 
#define cmdButtonTIC_LabelTitle_RESID 208
#define cmdButtonTIC_LabelDescription_RESID 209
#define cmdButtonTIC_TooltipTitle_RESID 210
#define cmdButtonTIC_TooltipDescription_RESID 211
#define cmdButtonTIC_LargeImages_RESID 212
#define cmdButtonToolkits 1007 
#define cmdButtonToolkits_LabelTitle_RESID 28
#define cmdButtonToolkits_LabelDescription_RESID 29
#define cmdButtonToolkits_TooltipTitle_RESID 30
#define cmdButtonToolkits_TooltipDescription_RESID 31
#define cmdButtonToolkits_SmallImages_RESID 32
#define cmdButtonToolkits_LargeImages_RESID 33
#define cmdButtonXIC 1145 
#define cmdButtonXIC_LabelTitle_RESID 213
#define cmdButtonXIC_LabelDescription_RESID 214
#define cmdButtonXIC_TooltipTitle_RESID 215
#define cmdButtonXIC_TooltipDescription_RESID 216
#define cmdButtonXIC_LargeImages_RESID 217
#define cmdComboFormulaSearchProfile3 1099 
#define cmdContextMap 1106 
#define cmdCustomizeQAT 1018 
#define cmdFontControl 1165 
#define cmdGroupAboutActions 1047 
#define cmdGroupAboutActions_LabelTitle_RESID 86
#define cmdGroupCalculator 1063 
#define cmdGroupCalculator_LabelTitle_RESID 103
#define cmdGroupChromatography 1141 
#define cmdGroupChromatography_LabelTitle_RESID 202
#define cmdGroupDemoActions 1048 
#define cmdGroupDemoActions_LabelTitle_RESID 87
#define cmdGroupDesign 1036 
#define cmdGroupDesign_LabelTitle_RESID 78
#define cmdGroupExactMassSearch 1073 
#define cmdGroupExactMassSearch_LabelTitle_RESID 111
#define cmdGroupExit 1096 
#define cmdGroupExit_LabelTitle_RESID 130
#define cmdGroupFileActions 1045 
#define cmdGroupFileActions_LabelTitle_RESID 84
#define cmdGroupFormulaSearch 1093 
#define cmdGroupFormulaSearch_LabelTitle_RESID 123
#define cmdGroupFormulaSearchConfig2 1095 
#define cmdGroupFormulaSearchConfig2_LabelTitle_RESID 129
#define cmdGroupLayout 1037 
#define cmdGroupLayout_LabelTitle_RESID 79
#define cmdGroupNetwork 1083 
#define cmdGroupNetwork_LabelTitle_RESID 116
#define cmdGroupNetworkRenderTool 1150 
#define cmdGroupNetworkRenderTool_LabelTitle_RESID 218
#define cmdGroupNetworkTools 1151 
#define cmdGroupNetworkTools_LabelTitle_RESID 219
#define cmdGroupRscript 1132 
#define cmdGroupRscript_LabelTitle_RESID 191
#define cmdGroupShowDockWindows 1120 
#define cmdGroupShowDockWindows_LabelTitle_RESID 176
#define cmdGroupShowViewer 1110 
#define cmdGroupShowViewer_LabelTitle_RESID 167
#define cmdGroupToolsActions 1046 
#define cmdGroupToolsActions_LabelTitle_RESID 85
#define cmdHelpButton 1016 
#define cmdLegendCheckBox 1166 
#define cmdLegendCheckBox_LabelTitle_RESID 229
#define cmdMenuGroupExit 1006 
#define cmdMenuGroupExit_LabelTitle_RESID 27
#define cmdMenuGroupFile 1005 
#define cmdMenuGroupFile_LabelTitle_RESID 26
#define cmdPPMSpinner 1050 
#define cmdPPMSpinner_LabelTitle_RESID 88
#define cmdQAT 1015 
#define cmdRecentItems 1014 
#define cmdRecentItems_LabelTitle_RESID 51
#define cmdSpinnerSimilarity 1153 
#define cmdSpinnerSimilarity_LabelTitle_RESID 220
#define cmdSpinnerSimilarity_LabelDescription_RESID 221
#define cmdSpinnerSimilarity_TooltipTitle_RESID 222
#define cmdSpinnerSimilarity_TooltipDescription_RESID 223
#define cmdTabAbout 1020 
#define cmdTabAbout_LabelTitle_RESID 65
#define cmdTabCalculator 1062 
#define cmdTabCalculator_LabelTitle_RESID 102
#define cmdTabDesign 1032 
#define cmdTabDesign_LabelTitle_RESID 76
#define cmdTabExactMassSearch 1072 
#define cmdTabExactMassSearch_LabelTitle_RESID 110
#define cmdTabFormulaSearch 1092 
#define cmdTabFormulaSearch_LabelTitle_RESID 122
#define cmdTabGroupCalculatorTools 1061 
#define cmdTabGroupCalculatorTools_LabelTitle_RESID 101
#define cmdTabGroupExactMassSearchTools 1071 
#define cmdTabGroupExactMassSearchTools_LabelTitle_RESID 109
#define cmdTabGroupFormulaSearchTools 1091 
#define cmdTabGroupFormulaSearchTools_LabelTitle_RESID 121
#define cmdTabGroupNetworkTools 1081 
#define cmdTabGroupNetworkTools_LabelTitle_RESID 114
#define cmdTabGroupRscriptTools 1130 
#define cmdTabGroupRscriptTools_LabelTitle_RESID 189
#define cmdTabGroupTableTools 1031 
#define cmdTabGroupTableTools_LabelTitle_RESID 75
#define cmdTabGroupWindowTools 1023 
#define cmdTabGroupWindowTools_LabelTitle_RESID 64
#define cmdTabLayout 1035 
#define cmdTabLayout_LabelTitle_RESID 77
#define cmdTabMain 1011 
#define cmdTabMain_LabelTitle_RESID 46
#define cmdTabNetwork 1082 
#define cmdTabNetwork_LabelTitle_RESID 115
#define cmdTabRscriptTools 1131 
#define cmdTabRscriptTools_LabelTitle_RESID 190
#define cmdTabTools 1012 
#define cmdTabTools_LabelTitle_RESID 47
#define cmdTweaksImage 93 
#define cmdTweaksImage_LabelTitle_RESID 240
#define cmdTweaksImage_LabelDescription_RESID 241
#define cmdTweaksImage_TooltipTitle_RESID 242
#define cmdTweaksImage_TooltipDescription_RESID 243
#define cmdTweaksImage_SmallImages_192__RESID 244
#define cmdTweaksImage_LargeImages_192__RESID 245
#define cmdGroupExport 2 
#define cmdGroupExport_LabelTitle_RESID 60001
#define cmdGroupExport_LabelDescription_RESID 60002
#define cmdGroupExport_TooltipTitle_RESID 60003
#define cmdGroupExport_TooltipDescription_RESID 60004
#define cmdGroupExport_SmallImages_192__RESID 60005
#define cmdGroupExport_LargeImages_192__RESID 60006
#define cmdShowProperty 3 
#define cmdShowProperty_LabelTitle_RESID 60007
#define cmdShowProperty_LabelDescription_RESID 60008
#define cmdShowProperty_TooltipTitle_RESID 60009
#define cmdShowProperty_TooltipDescription_RESID 60010
#define cmdShowProperty_SmallImages_192__RESID 60011
#define cmdShowProperty_LargeImages_192__RESID 60012
#define cmdCheckBoxXICRelative 96 
#define cmdCheckBoxXICRelative_LabelTitle_RESID 60013
#define cmdCheckBoxXICRelative_LabelDescription_RESID 60014
#define cmdCheckBoxXICRelative_TooltipTitle_RESID 60015
#define cmdCheckBoxXICRelative_TooltipDescription_RESID 60016
#define cmdPlotOptions 97 
#define cmdPlotOptions_LabelTitle_RESID 60017
#define cmdPlotOptions_LabelDescription_RESID 60018
#define cmdPlotOptions_TooltipTitle_RESID 60019
#define cmdPlotOptions_TooltipDescription_RESID 60020
#define InternalCmd2_LabelTitle_RESID 60021
#define InternalCmd4_LabelTitle_RESID 60022
